extends CardScript
## Flying Men — {U} — Creature — Human — 1/1 — (arn, common)
## Oracle: Flying
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Flying Men", "{U}", Mtg.CardType.CREATURE) \
		.pt(1, 1) \
		.with_subtypes(["human"]) \
		.with_keywords([Mtg.Keyword.FLYING]) \
		.oracle("Flying")
