extends CardScript
## Moorish Cavalry — {2}{W}{W} — Creature — Human Knight — 3/3 — (arn, common)
## Oracle: Trample
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Moorish Cavalry", "{2}{W}{W}", Mtg.CardType.CREATURE) \
		.pt(3, 3) \
		.with_subtypes(["human", "knight"]) \
		.with_keywords([Mtg.Keyword.TRAMPLE]) \
		.oracle("Trample")
