extends CardScript
## Repentant Blacksmith — {1}{W} — Creature — Human — 1/2 — (arn, rare)
## Oracle: Protection from red
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Repentant Blacksmith", "{1}{W}", Mtg.CardType.CREATURE) \
		.pt(1, 2) \
		.with_subtypes(["human"]) \
		.with_protection_from(Mtg.ManaColor.R) \
		.oracle("Protection from red")
