extends CardScript
## Stone-Throwing Devils — {B} — Creature — Devil — 1/1 — (arn, common)
## Oracle: First strike
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Stone-Throwing Devils", "{B}", Mtg.CardType.CREATURE) \
		.pt(1, 1) \
		.with_subtypes(["devil"]) \
		.with_keywords([Mtg.Keyword.FIRST_STRIKE]) \
		.oracle("First strike")
