extends CardScript
## War Elephant — {3}{W} — Creature — Elephant — 2/2 — (arn, common)
## Oracle: Trample; banding (Any creatures with banding, and up to one without, can attack in a band. Bands are blocked as a group. If any creatures with banding you control are blocking or being blocked by a creature, you divide that creature's combat damage, not its controller, among any of the creatures it's being blocked by or is blocking.)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("War Elephant", "{3}{W}", Mtg.CardType.CREATURE) \
		.pt(2, 2) \
		.with_subtypes(["elephant"]) \
		.with_keywords([Mtg.Keyword.TRAMPLE, Mtg.Keyword.BANDING]) \
		.oracle("Trample; banding (Any creatures with banding, and up to one without, can attack in a band. Bands are blocked as a group. If any creatures with banding you control are blocking or being blocked by a creature, you divide that creature's combat damage, not its controller, among any of the creatures it's being blocked by or is blocking.)")
