extends CardScript
## Windseeker Centaur — {1}{R}{R} — Creature — Centaur — 2/2 — (phpr, rare)
## Oracle: Vigilance
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Windseeker Centaur", "{1}{R}{R}", Mtg.CardType.CREATURE) \
		.pt(2, 2) \
		.with_subtypes(["centaur"]) \
		.with_keywords([Mtg.Keyword.VIGILANCE]) \
		.oracle("Vigilance")
