extends CardScript
## Azure Drake — {3}{U} — Creature — Drake — 2/4 — (leg, uncommon)
## Oracle: Flying
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Azure Drake", "{3}{U}", Mtg.CardType.CREATURE) \
		.pt(2, 4) \
		.with_subtypes(["drake"]) \
		.with_keywords([Mtg.Keyword.FLYING]) \
		.oracle("Flying")
