extends CardScript
## Barbary Apes — {1}{G} — Creature — Ape — 2/2 — (leg, common)
## Oracle: (no rules text — vanilla creature)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Barbary Apes", "{1}{G}", Mtg.CardType.CREATURE) \
		.pt(2, 2) \
		.with_subtypes(["ape"]) \
		.oracle("")
