extends CardScript
## Barktooth Warbeard — {4}{B}{R}{R} — Legendary Creature — Human Warrior — 6/5 — (leg, uncommon)
## Oracle: (no rules text — vanilla creature)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Barktooth Warbeard", "{4}{B}{R}{R}", Mtg.CardType.CREATURE) \
		.pt(6, 5) \
		.with_supertypes(Mtg.Supertype.LEGENDARY) \
		.with_subtypes(["human", "warrior"]) \
		.oracle("")
