extends CardScript
## Cat Warriors — {1}{G}{G} — Creature — Cat Warrior — 2/2 — (leg, common)
## Oracle: Forestwalk (This creature can't be blocked as long as defending player controls a Forest.)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Cat Warriors", "{1}{G}{G}", Mtg.CardType.CREATURE) \
		.pt(2, 2) \
		.with_subtypes(["cat", "warrior"]) \
		.with_landwalk(["forest"]) \
		.oracle("Forestwalk (This creature can't be blocked as long as defending player controls a Forest.)")
