extends CardScript
## Devouring Deep — {2}{U} — Creature — Fish — 1/2 — (leg, common)
## Oracle: Islandwalk (This creature can't be blocked as long as defending player controls an Island.)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Devouring Deep", "{2}{U}", Mtg.CardType.CREATURE) \
		.pt(1, 2) \
		.with_subtypes(["fish"]) \
		.with_landwalk(["island"]) \
		.oracle("Islandwalk (This creature can't be blocked as long as defending player controls an Island.)")
