extends CardScript
## Headless Horseman — {2}{B} — Creature — Zombie Knight — 2/2 — (leg, common)
## Oracle: (no rules text — vanilla creature)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Headless Horseman", "{2}{B}", Mtg.CardType.CREATURE) \
		.pt(2, 2) \
		.with_subtypes(["zombie", "knight"]) \
		.oracle("")
