extends CardScript
## Hornet Cobra — {1}{G}{G} — Creature — Snake — 2/1 — (leg, common)
## Oracle: First strike
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Hornet Cobra", "{1}{G}{G}", Mtg.CardType.CREATURE) \
		.pt(2, 1) \
		.with_subtypes(["snake"]) \
		.with_keywords([Mtg.Keyword.FIRST_STRIKE]) \
		.oracle("First strike")
