extends CardScript
## Jasmine Boreal — {3}{G}{W} — Legendary Creature — Human — 4/5 — (leg, uncommon)
## Oracle: (no rules text — vanilla creature)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Jasmine Boreal", "{3}{G}{W}", Mtg.CardType.CREATURE) \
		.pt(4, 5) \
		.with_supertypes(Mtg.Supertype.LEGENDARY) \
		.with_subtypes(["human"]) \
		.oracle("")
