extends CardScript
## Jedit Ojanen — {4}{W}{W}{U} — Legendary Creature — Cat Warrior — 5/5 — (leg, uncommon)
## Oracle: (no rules text — vanilla creature)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Jedit Ojanen", "{4}{W}{W}{U}", Mtg.CardType.CREATURE) \
		.pt(5, 5) \
		.with_supertypes(Mtg.Supertype.LEGENDARY) \
		.with_subtypes(["cat", "warrior"]) \
		.oracle("")
