extends CardScript
## Jerrard of the Closed Fist — {3}{R}{G}{G} — Legendary Creature — Human Knight — 6/5 — (leg, uncommon)
## Oracle: (no rules text — vanilla creature)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Jerrard of the Closed Fist", "{3}{R}{G}{G}", Mtg.CardType.CREATURE) \
		.pt(6, 5) \
		.with_supertypes(Mtg.Supertype.LEGENDARY) \
		.with_subtypes(["human", "knight"]) \
		.oracle("")
