extends CardScript
## Kasimir the Lone Wolf — {4}{W}{U} — Legendary Creature — Human Warrior — 5/3 — (leg, uncommon)
## Oracle: (no rules text — vanilla creature)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Kasimir the Lone Wolf", "{4}{W}{U}", Mtg.CardType.CREATURE) \
		.pt(5, 3) \
		.with_supertypes(Mtg.Supertype.LEGENDARY) \
		.with_subtypes(["human", "warrior"]) \
		.oracle("")
