extends CardScript
## Kobolds of Kher Keep — {0} — Creature — Kobold — 0/1 — (leg, common)
## Oracle: (no rules text — vanilla creature)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Kobolds of Kher Keep", "{0}", Mtg.CardType.CREATURE) \
		.pt(0, 1) \
		.with_subtypes(["kobold"]) \
		.with_colors(Mtg.ManaColor.R) \
		.oracle("")
