extends CardScript
## Lady Orca — {5}{B}{R} — Legendary Creature — Demon — 7/4 — (leg, uncommon)
## Oracle: (no rules text — vanilla creature)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Lady Orca", "{5}{B}{R}", Mtg.CardType.CREATURE) \
		.pt(7, 4) \
		.with_supertypes(Mtg.Supertype.LEGENDARY) \
		.with_subtypes(["demon"]) \
		.oracle("")
