extends CardScript
## Moss Monster — {3}{G}{G} — Creature — Elemental — 3/6 — (leg, common)
## Oracle: (no rules text — vanilla creature)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Moss Monster", "{3}{G}{G}", Mtg.CardType.CREATURE) \
		.pt(3, 6) \
		.with_subtypes(["elemental"]) \
		.oracle("")
