extends CardScript
## Mountain Yeti — {2}{R}{R} — Creature — Yeti — 3/3 — (leg, uncommon)
## Oracle: Mountainwalk (This creature can't be blocked as long as defending player controls a Mountain.)
##         Protection from white
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Mountain Yeti", "{2}{R}{R}", Mtg.CardType.CREATURE) \
		.pt(3, 3) \
		.with_subtypes(["yeti"]) \
		.with_protection_from(Mtg.ManaColor.W) \
		.with_landwalk(["mountain"]) \
		.oracle("Mountainwalk (This creature can't be blocked as long as defending player controls a Mountain.)\nProtection from white")
