extends CardScript
## Ramirez DePietro — {3}{U}{B}{B} — Legendary Creature — Human Pirate — 4/3 — (leg, uncommon)
## Oracle: First strike
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Ramirez DePietro", "{3}{U}{B}{B}", Mtg.CardType.CREATURE) \
		.pt(4, 3) \
		.with_supertypes(Mtg.Supertype.LEGENDARY) \
		.with_subtypes(["human", "pirate"]) \
		.with_keywords([Mtg.Keyword.FIRST_STRIKE]) \
		.oracle("First strike")
