extends CardScript
## Righteous Avengers — {4}{W} — Creature — Human Soldier — 3/1 — (leg, uncommon)
## Oracle: Plainswalk (This creature can't be blocked as long as defending player controls a Plains.)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Righteous Avengers", "{4}{W}", Mtg.CardType.CREATURE) \
		.pt(3, 1) \
		.with_subtypes(["human", "soldier"]) \
		.with_landwalk(["plains"]) \
		.oracle("Plainswalk (This creature can't be blocked as long as defending player controls a Plains.)")
