extends CardScript
## Sir Shandlar of Eberyn — {4}{G}{W} — Legendary Creature — Human Knight — 4/7 — (leg, uncommon)
## Oracle: (no rules text — vanilla creature)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Sir Shandlar of Eberyn", "{4}{G}{W}", Mtg.CardType.CREATURE) \
		.pt(4, 7) \
		.with_supertypes(Mtg.Supertype.LEGENDARY) \
		.with_subtypes(["human", "knight"]) \
		.oracle("")
