extends CardScript
## Sivitri Scarzam — {5}{U}{B} — Legendary Creature — Human — 6/4 — (leg, uncommon)
## Oracle: (no rules text — vanilla creature)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Sivitri Scarzam", "{5}{U}{B}", Mtg.CardType.CREATURE) \
		.pt(6, 4) \
		.with_supertypes(Mtg.Supertype.LEGENDARY) \
		.with_subtypes(["human"]) \
		.oracle("")
