extends CardScript
## The Lady of the Mountain — {4}{R}{G} — Legendary Creature — Giant — 5/5 — (leg, uncommon)
## Oracle: (no rules text — vanilla creature)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("The Lady of the Mountain", "{4}{R}{G}", Mtg.CardType.CREATURE) \
		.pt(5, 5) \
		.with_supertypes(Mtg.Supertype.LEGENDARY) \
		.with_subtypes(["giant"]) \
		.oracle("")
