extends CardScript
## Thunder Spirit — {1}{W}{W} — Creature — Elemental Spirit — 2/2 — (leg, rare)
## Oracle: Flying, first strike
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Thunder Spirit", "{1}{W}{W}", Mtg.CardType.CREATURE) \
		.pt(2, 2) \
		.with_subtypes(["elemental", "spirit"]) \
		.with_keywords([Mtg.Keyword.FLYING, Mtg.Keyword.FIRST_STRIKE]) \
		.oracle("Flying, first strike")
