extends CardScript
## Wall of Heat — {2}{R} — Creature — Wall — 2/6 — (leg, common)
## Oracle: Defender (This creature can't attack.)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Wall of Heat", "{2}{R}", Mtg.CardType.CREATURE) \
		.pt(2, 6) \
		.with_subtypes(["wall"]) \
		.with_keywords([Mtg.Keyword.DEFENDER]) \
		.oracle("Defender (This creature can't attack.)")
