extends CardScript
## Wall of Light — {2}{W} — Creature — Wall — 1/5 — (leg, uncommon)
## Oracle: Defender (This creature can't attack.)
##         Protection from black
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Wall of Light", "{2}{W}", Mtg.CardType.CREATURE) \
		.pt(1, 5) \
		.with_subtypes(["wall"]) \
		.with_keywords([Mtg.Keyword.DEFENDER]) \
		.with_protection_from(Mtg.ManaColor.B) \
		.oracle("Defender (This creature can't attack.)\nProtection from black")
