extends CardScript
## Craw Wurm — {4}{G}{G} — Creature — Wurm — 6/4 — (2ed, common)
## Oracle: (no rules text — vanilla creature)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Craw Wurm", "{4}{G}{G}", Mtg.CardType.CREATURE) \
		.pt(6, 4) \
		.with_subtypes(["wurm"]) \
		.oracle("")
