extends CardScript
## Earth Elemental — {3}{R}{R} — Creature — Elemental — 4/5 — (2ed, uncommon)
## Oracle: (no rules text — vanilla creature)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Earth Elemental", "{3}{R}{R}", Mtg.CardType.CREATURE) \
		.pt(4, 5) \
		.with_subtypes(["elemental"]) \
		.oracle("")
