extends CardScript
## Giant Spider — {3}{G} — Creature — Spider — 2/4 — (2ed, common)
## Oracle: Reach (This creature can block creatures with flying.)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Giant Spider", "{3}{G}", Mtg.CardType.CREATURE) \
		.pt(2, 4) \
		.with_subtypes(["spider"]) \
		.with_keywords([Mtg.Keyword.REACH]) \
		.oracle("Reach (This creature can block creatures with flying.)")
