extends CardScript
## Hill Giant — {3}{R} — Creature — Giant — 3/3 — (2ed, common)
## Oracle: (no rules text — vanilla creature)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Hill Giant", "{3}{R}", Mtg.CardType.CREATURE) \
		.pt(3, 3) \
		.with_subtypes(["giant"]) \
		.oracle("")
