extends CardScript
## Hurloon Minotaur — {1}{R}{R} — Creature — Minotaur — 2/3 — (2ed, common)
## Oracle: (no rules text — vanilla creature)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Hurloon Minotaur", "{1}{R}{R}", Mtg.CardType.CREATURE) \
		.pt(2, 3) \
		.with_subtypes(["minotaur"]) \
		.oracle("")
