extends CardScript
## Ironroot Treefolk — {4}{G} — Creature — Treefolk — 3/5 — (2ed, common)
## Oracle: (no rules text — vanilla creature)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Ironroot Treefolk", "{4}{G}", Mtg.CardType.CREATURE) \
		.pt(3, 5) \
		.with_subtypes(["treefolk"]) \
		.oracle("")
