extends CardScript
## Mahamoti Djinn — {4}{U}{U} — Creature — Djinn — 5/6 — (2ed, rare)
## Oracle: Flying (This creature can't be blocked except by creatures with flying or reach.)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Mahamoti Djinn", "{4}{U}{U}", Mtg.CardType.CREATURE) \
		.pt(5, 6) \
		.with_subtypes(["djinn"]) \
		.with_keywords([Mtg.Keyword.FLYING]) \
		.oracle("Flying (This creature can't be blocked except by creatures with flying or reach.)")
