extends CardScript
## Merfolk of the Pearl Trident — {U} — Creature — Merfolk — 1/1 — (2ed, common)
## Oracle: (no rules text — vanilla creature)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Merfolk of the Pearl Trident", "{U}", Mtg.CardType.CREATURE) \
		.pt(1, 1) \
		.with_subtypes(["merfolk"]) \
		.oracle("")
