extends CardScript
## Obsianus Golem — {6} — Artifact Creature — Golem — 4/6 — (2ed, uncommon)
## Oracle: (no rules text — vanilla creature)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Obsianus Golem", "{6}", Mtg.CardType.ARTIFACT | Mtg.CardType.CREATURE) \
		.pt(4, 6) \
		.with_subtypes(["golem"]) \
		.oracle("")
