extends CardScript
## Pearled Unicorn — {2}{W} — Creature — Unicorn — 2/2 — (2ed, common)
## Oracle: (no rules text — vanilla creature)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Pearled Unicorn", "{2}{W}", Mtg.CardType.CREATURE) \
		.pt(2, 2) \
		.with_subtypes(["unicorn"]) \
		.oracle("")
