extends CardScript
## Phantom Monster — {3}{U} — Creature — Illusion — 3/3 — (2ed, uncommon)
## Oracle: Flying
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Phantom Monster", "{3}{U}", Mtg.CardType.CREATURE) \
		.pt(3, 3) \
		.with_subtypes(["illusion"]) \
		.with_keywords([Mtg.Keyword.FLYING]) \
		.oracle("Flying")
