extends CardScript
## Roc of Kher Ridges — {3}{R} — Creature — Bird — 3/3 — (2ed, rare)
## Oracle: Flying
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Roc of Kher Ridges", "{3}{R}", Mtg.CardType.CREATURE) \
		.pt(3, 3) \
		.with_subtypes(["bird"]) \
		.with_keywords([Mtg.Keyword.FLYING]) \
		.oracle("Flying")
