extends CardScript
## Scryb Sprites — {G} — Creature — Faerie — 1/1 — (2ed, common)
## Oracle: Flying
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Scryb Sprites", "{G}", Mtg.CardType.CREATURE) \
		.pt(1, 1) \
		.with_subtypes(["faerie"]) \
		.with_keywords([Mtg.Keyword.FLYING]) \
		.oracle("Flying")
