extends CardScript
## Wall of Ice — {2}{G} — Creature — Wall — 0/7 — (2ed, uncommon)
## Oracle: Defender (This creature can't attack.)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Wall of Ice", "{2}{G}", Mtg.CardType.CREATURE) \
		.pt(0, 7) \
		.with_subtypes(["wall"]) \
		.with_keywords([Mtg.Keyword.DEFENDER]) \
		.oracle("Defender (This creature can't attack.)")
