extends CardScript
## Wall of Wood — {G} — Creature — Wall — 0/3 — (2ed, common)
## Oracle: Defender (This creature can't attack.)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Wall of Wood", "{G}", Mtg.CardType.CREATURE) \
		.pt(0, 3) \
		.with_subtypes(["wall"]) \
		.with_keywords([Mtg.Keyword.DEFENDER]) \
		.oracle("Defender (This creature can't attack.)")
