extends CardScript
## Wall of Stone — {1}{R}{R} — Creature — Wall — 0/8 — (2ed, uncommon)
## Oracle: Defender (This creature can't attack.)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Wall of Stone", "{1}{R}{R}", Mtg.CardType.CREATURE) \
		.pt(0, 8) \
		.with_subtypes(["wall"]) \
		.with_keywords([Mtg.Keyword.DEFENDER]) \
		.oracle("Defender (This creature can't attack.)")
