extends CardScript
## Wall of Swords — {3}{W} — Creature — Wall — 3/5 — (2ed, uncommon)
## Oracle: Defender (This creature can't attack.)
##         Flying
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Wall of Swords", "{3}{W}", Mtg.CardType.CREATURE) \
		.pt(3, 5) \
		.with_subtypes(["wall"]) \
		.with_keywords([Mtg.Keyword.DEFENDER, Mtg.Keyword.FLYING]) \
		.oracle("Defender (This creature can't attack.)\nFlying")
