extends CardScript
## Wall of Air — {1}{U}{U} — Creature — Wall — 1/5 — (2ed, uncommon)
## Oracle: Defender, flying (This creature can't attack, and it can block creatures with flying.)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Wall of Air", "{1}{U}{U}", Mtg.CardType.CREATURE) \
		.pt(1, 5) \
		.with_subtypes(["wall"]) \
		.with_keywords([Mtg.Keyword.DEFENDER, Mtg.Keyword.FLYING]) \
		.oracle("Defender, flying (This creature can't attack, and it can block creatures with flying.)")
