extends CardScript
## Water Elemental — {3}{U}{U} — Creature — Elemental — 5/4 — (2ed, uncommon)
## Oracle: (no rules text — vanilla creature)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Water Elemental", "{3}{U}{U}", Mtg.CardType.CREATURE) \
		.pt(5, 4) \
		.with_subtypes(["elemental"]) \
		.oracle("")
