extends RefCounted
## The final Help chapter: player-facing rules, not implementation notes.
## Verified against engine/combat.gd, the effect classes, fem/_rules.gd and
## Wizards' Comprehensive Rules (magic.wizards.com/en/rules), especially
## combat, keyword abilities, costs, counters and delayed triggers.
## Keep examples textual so this reference also works with packs disabled.

static func portal_intro() -> Dictionary:
	return _page("Portal — A first step into Magic", [
			["Original Portal, 1997", "Pack 6 adds the original Portal set: straightforward creatures, spells and beautiful basic lands. Enable it in Options → Card Packs, then choose Portal in Deck Builder → Extras. Turn the other sources off to browse its 200 different cards and 215 printings. Select a card, then use the Card variant stone medallion just below the large preview's lower-right corner to choose artwork, including four versions of each basic land. Your saved deck remembers the choice."],
			["Read the current rules", "The original pictures preserve their printed wording. Gameplay uses current card types and rules. Some cards printed as sorceries are now instants. Assassin's Blade, Deep Wood and similar tricks can be cast only after an opponent attacks you, during Declare Attackers — before blockers are declared."],
			["More lands and fewer blockers", "Summer Bloom allows three additional land plays this turn. Charging Rhino and Stalking Tiger cannot be blocked by more than one creature. If such a creature also requires two or more blockers, it cannot be blocked."],
			["Last Chance", "Last Chance grants an extra turn, but you lose at the beginning of that turn's end step. The most recently created extra turn happens first. A normal Time Walk turn does not inherit Last Chance's loss condition."],
			["The large mana symbols", "Portal basic-land previews retain the original printed card and its large mana symbol. Animated lands show the live game frame so their creature statistics remain visible. Saved decks remember one chosen printing per card name."],
		])


static func pages() -> Array:
	return [
		_page("Abilities — Combat", [
			["Flying and reach", "A flying attacker can be blocked only by creatures with flying or reach. Reach does not let a creature fly. Giving flying after blockers are chosen does not remove an existing block."],
			["First strike", "First strikers deal combat damage before creatures without first strike. A creature killed by that early damage does not strike back. First strike does not double the damage."],
			["Trample", "An attacker can assign excess combat damage to the defending player after assigning lethal damage to its blockers. Without trample, an attacker that became blocked normally stays blocked even if its blockers leave."],
			["Vigilance, haste and defender", "Vigilance means attacking does not tap the creature. Haste removes the usual summoning-sickness restriction on attacking and tap-symbol abilities. Defender prevents attacking unless another effect specifically allows it."],
			["Landwalk and menace", "Landwalk makes an attacker unblockable while the defender controls the named land type. Menace means it cannot be blocked by just one creature: the defender needs at least two legal blockers. Goblin War Drums gives this blocking restriction to your creatures."],
		]),
		_page("Abilities — Banding and protection", [
			["Banding when attacking", "You may group creatures with banding and up to one creature without banding into an attacking band. If a creature blocks a member, the whole band becomes blocked. Band members do not share flying, trample or other abilities."],
			["Banding changes damage assignment", "When an attacking band includes banding, its controller chooses how its blockers assign damage among that band. A defending creature with banding similarly lets its controller assign the blocked attacker's damage. Banding does not merge the creatures or their toughness."],
			["Protection", "Protection from a quality prevents damage from matching sources, stops matching Auras from enchanting the creature, stops matching creatures from blocking it, and stops matching spells or abilities from targeting it. Protection from black does not stop every black effect: a non-targeting destroy-all effect can still destroy it."],
			["Shroud", "A permanent with shroud cannot be targeted by either player's spells or abilities, including your own. It can still be affected by effects that do not target. Deep Spawn and Homarid Warrior can gain temporary shroud, but their abilities also tap them and delay their next untap."],
		]),
		_page("Abilities — Costs, triggers and survival", [
			["Activated abilities: cost : effect", "Pay everything before the colon when you activate: mana, tapping, sacrifices, discards or counter removal. Those costs are not returned if the ability is countered or loses its target. A tap-symbol cost needs an untapped source; a summoning-sick creature cannot pay it without haste."],
			["Triggered and static abilities", "When, whenever and at usually introduce triggered abilities. They wait on the Spell Chain and can be answered. Static abilities apply continuously while their conditions hold, without an activation. Mana abilities normally produce mana immediately rather than waiting on the chain."],
			["Regeneration", "Regeneration replaces destruction: tap the creature, remove its marked damage and remove it from combat. It does not return a dead creature. With modern damage timing, create the shield before lethal damage; with classic damage timing, use the regeneration window. Regeneration cannot stop sacrifice, exile, zero toughness or an effect that forbids regeneration."],
			["Counters and temporary boosts", "Counters stay on a permanent until removed or until it leaves the battlefield. A +1/+1 counter changes both stats; +1/+0 and +0/+1 counters change only one. An until-end-of-turn boost expires at cleanup instead. Damage is not a counter and does not reduce the displayed toughness."],
			["Tokens and creature types", "A token is a permanent and follows its creature's normal rules, including summoning sickness. A token that leaves the battlefield cannot later return. Creature types such as Thrull, Goblin, Merfolk and Fungus matter only when a card refers to them; sharing a type does not give creatures shared abilities."],
		]),
		_page("Abilities — Fallen Empires resources", [
			["Spore counters", "Thallids and related creatures gain spore counters during your upkeep. Remove three to pay for the printed ability: making a Saproling, dealing damage, preventing combat damage or regenerating. Spore counters alone do not increase power or toughness. Fungal Bloom adds a spore counter to a Fungus."],
			["Storage lands", "These lands enter tapped. You may leave one tapped during your untap step, and it gains a storage counter during your upkeep if it is tapped. Once untapped, use its mana ability and remove the chosen number of storage counters to produce that much mana."],
			["Mana conversion and High Tide", "Initiates of the Ebon Hand and Farrelite Priest turn one mana into the printed color without tapping. Using one at least four times in a turn creates a sacrifice trigger for the next end step. Implements of Sacrifice costs one mana, tapping and sacrificing itself to make two mana of one color. High Tide adds blue mana when an Island is tapped for mana that turn."],
			["Tide, net, time and credit counters", "Homarid and Tidal Influence change their effects as tide counters rise, then reset. Merseine's net counters keep its host from untapping; the host's controller may pay to remove them. Tourach's Gate consumes time counters at upkeep. Icatian Moneychanger stores credit counters that its sacrifice ability turns into life."],
		]),
		_page("Abilities — Fallen Empires combat tricks", [
			["Sacrifices and crew taps", "Goblin Warrens sacrifices two Goblins to make three. Night Soil exiles two creature cards from one graveyard to make a Saproling. War Machine and Hand of Justice require other creatures to tap as costs. A cost that says to tap an eligible creature is different from that creature paying its own tap symbol, so newly arrived helpers can be used."],
			["Unblocked-attack abilities", "Farrel's Zealot, Farrel's Mantle, Mindstab Thrull and Necrite trigger after blockers are declared if their attacker is unblocked. Delif's artifacts first set up a delayed trigger. Read whether the card replaces combat-damage assignment, prevents damage, or sacrifices the attacker: these are different effects."],
			["Effects that last while a condition holds", "Seasinger's control lasts while it remains tapped and under your control; Thrull Champion also needs you to keep control of the Champion. Spirit Shield and Zelyon Sword maintain their bonuses while tapped. Untapping or losing the required control ends the effect; tapping or taking the source back does not restart it."],
			["Coin flips and delayed effects", "Goblin Kites grants flying now, then flips a coin at the next end step; losing means sacrificing that creature if you still control it. Orcish Captain flips for a bonus or penalty. These are genuine random outcomes. Rainbow Vale gives its mana now and changes control through a later end-step trigger."],
			["New objects, not returned effects", "A card that leaves the battlefield and returns is a new permanent. Old counters, temporary effects and abilities waiting to affect its previous incarnation do not automatically follow it back. An ability already on the Spell Chain can still resolve even if its source leaves."],
		]),
		_page("Abilities — Ice Age resources", [
			["Snow lands", "Snow is a supertype, not a sixth mana color. Snow-Covered Island is still a basic Island and makes blue mana. A card counts snow lands only when its instructions say so. Snow landwalk checks the defending player's snow land of the named type."],
			["Cumulative upkeep", "At the beginning of your upkeep, put an age counter on that permanent. Then pay its upkeep cost once for each age counter, or sacrifice it. The whole payment is optional but must be paid in full. Multiple cumulative-upkeep abilities trigger separately and use the same age counters. Sacrifice cannot be regenerated."],
			["Restricted mana", "Adarkar Unicorn and Snowfall can produce mana usable only for cumulative upkeep. Soldevi Machinist's mana is only for activated abilities of artifacts, not for casting artifact spells. The game keeps restricted mana separate and checks what you are paying for."],
			["Delayed card draws", "Many Ice Age spells draw at the beginning of the next turn's upkeep, not immediately. The draw is already scheduled even if its source leaves play. If every target of the original spell becomes illegal, that spell does not resolve and does not schedule its draw."],
			["Wind counters and one-time abilities", "Freyalise's Winds adds a counter when a permanent becomes tapped. During its controller's untap step, removing all wind counters replaces untapping it. Other untap effects still work normally. Goblin Ski Patrol says activate only once: countering that activation does not restore the use. Leaving and returning creates a new object."],
		]),
		_page("Abilities — Ice Age zones and control", [
			["Abilities in the graveyard", "Most abilities work only on the battlefield. Ashen Ghoul and Whiteout explicitly let you activate from your graveyard; their timing and costs still apply. A graveyard ability on the Spell Chain does not give every other card in that graveyard permission to act."],
			["Playing cards from exile", "Exile does not normally let you play a card. Elkin Bottle and Ice Cauldron give permission for the particular exiled card. Normal costs and timing still apply, including the land-per-turn limit. Face-down exiled cards stay hidden unless an effect lets a player look at them."],
			["Storing mana", "Jeweled Amulet remembers the mana type actually paid to charge it. Ice Cauldron remembers the amounts and types paid and releases mana usable only for its last exiled card. Removing the artifact does not cancel the permission to cast a card already exiled with it."],
			["Borrowing and holding permanents", "Ray of Command and Magus of the Unseen borrow until end of turn and later tap the returned permanent through a trigger. Merieke's control ends when you lose control of Merieke, but her destruction trigger waits until she untaps or leaves. A newer control effect can override an older one; ending it reveals any older effect that is still valid."],
			["Claims on dead creatures", "Krovikan Vampire checks at each end step for creatures it damaged that died that turn. Seraph first triggers when a damaged creature dies, then schedules the return. The card must remain in that graveyard. Leaving and returning makes a new object: old damage and old claims do not follow a fresh incarnation."],
		]),
		_page("Abilities — Ice Age combat and adaptations", [
			["Attacking and blocking costs", "Orcish Conscripts needs at least two other attacking creatures to attack, or two other blocking creatures to block. Errantry's host can attack only alone. Flooded Woodlands and Reclamation charge land sacrifices to attack with the named color; you may decline to attack instead. Hipparion charges mana to block a creature with power 3 or greater."],
			["Melee and General Jarkeld", "Melee lets the attacker choose the defender's blocks for that combat; the defender still decides whether to pay any blocking costs. Unblocked attackers are untapped and removed from combat through triggered abilities. General Jarkeld exchanges the blockers of two blocked attackers only if the new blocks are legal."],
			["Gaze of Pain", "Each unblocked attacker gets a targeted trigger. You may have that creature deal damage equal to its power to the target creature; if you do, it assigns no combat damage that turn. This is not combat damage, and a creature that was blocked does not qualify just because its blocker later leaves."],
			["Drought and Soul Burn", "Drought adds Swamp sacrifices for each printed black mana symbol in a spell's cost or an ability's activation cost. Soul Burn's X is not extra black symbols: it accepts only actual black or red mana. Cost reductions can reduce what you pay for X without reducing X's damage; life gain counts only black mana actually spent on X and is capped by the damage and the victim's life or toughness."],
			["Documented digital adaptations", "Balduvian Shaman changes a color only on one of the five colored Circles of Protection you control; it cannot rewrite arbitrary enchantment text. It still grants cumulative upkeep. Game of Chaos stops after 30 flips in one resolution. These differences are also printed on the digital cards."],
		]),
		_page("Abilities — Homelands resources and locks", [
			["Finite counters", "Serrated Arrows starts with three arrowheads; removing one pays for a -1/-1 counter on a creature. At your upkeep, an empty Arrows is sacrificed. Clockwork Steed and Swarm lose a +1/+0 counter at end of combat after participating; their X-and-tap ability recharges only during your upkeep, to at most four counters."],
			["Giant Oyster", "Target a tapped creature. While the Oyster remains tapped, that creature skips normal untapping and receives a -1/-1 counter in each of your draw steps. Untapping or removing the Oyster ends the lock and triggers removal of all -1/-1 counters on that creature. Tapping the Oyster again does not restart the old effect."],
			["Putting cards into play", "Didgeridoo and Willow Priestess put eligible cards from your hand directly onto the battlefield. This is not casting a spell, so Aether Storm does not stop it. Ordinary entry triggers and summoning sickness still apply. Any player may pay four life to activate Aether Storm's destruction ability."],
			["Taxes and untap restrictions", "Koskun Falls charges two mana for each creature attacking its controller. Paying for one attacker does not pay for the rest. Some cards say your next untap step, while others refer to the affected creature's next normal untap. Changing control does not turn those phrases into the same instruction."],
		]),
		_page("Abilities — Homelands combat and ownership", [
			["Damage redirection", "Hazduhr the Abbot redirects up to the chosen X damage from a white creature you control to himself. Daughter of Autumn redirects the next one damage from any target white creature. Damage keeps its original source and combat status. Protection and prevention still apply to its new recipient; redirection is not a toughness bonus."],
			["Shroud permission", "Autumn Willow has shroud. Her green-mana ability gives the chosen player permission to target her for that turn; it does not remove shroud for everyone. Effects that do not target need no such permission."],
			["Badger and graveyard targets", "Rysorian Badger may target up to two creature cards in the defending player's graveyard when it attacks unblocked. Exiling them gains one life per card actually exiled, but the Badger then assigns no combat damage that turn. You can choose zero targets or decline the exchange."],
			["Ownership and the digital adaptation", "Timmerian Fiends lets the artifact's owner ante the top card of their library instead of exchanging ownership. Otherwise both cards go to their new owners' graveyards, even if the Fiends has moved elsewhere. Ownership differs from battlefield control. Digital adaptation: token copies cannot participate in this exchange; the restriction is also printed on the card and listed in the simplified-card ledger."],
		]),
		_page("Abilities — Alliances costs and resources", [
			["Pitch spells", "Force of Will, Pyrokinesis, Contagion, Bounty of the Hunt and Scars of the Veteran offer an alternative to their mana cost: exile another card of the required color from your hand. Force of Will and Contagion also cost one life. Choose the payment mode before targets and payment; extra taxes still apply. Their printed mana values do not become zero."],
			["Mana from your hand", "Elvish Spirit Guide can be exiled from your hand to add one green mana without using the Spell Chain. Its ability does not work from the battlefield. It cannot pay for casting itself."],
			["Library and object costs", "Some abilities exile cards from the top of your library as a cost, before anyone can respond. You need enough cards to pay. Viscerid Drone needs both a creature and a separate Swamp; its snow-Swamp ability can also destroy artifact creatures. A tap-enchanted-creature cost is not a tap-symbol ability of that creature, so summoning sickness does not stop it."],
			["Variable and repeated costs", "Gorilla Shaman pays twice X plus one to destroy a noncreature artifact whose mana value is X. Primitive Justice pays an extra one generic plus red or green for each additional artifact target; green payments also gain life. Taste of Paradise lets you pay one generic and one green repeatedly for three extra life each time."],
			["Hidden piles and linked cards", "Phyrexian Portal lets the opponent inspect ten cards and split them; the library's owner chooses which pile to exile without seeing its cards. Gustha's Scepter exiles a hand card face down and only its controller at that time may inspect it. Losing control of the Scepter or removing it sends its linked cards to their owners' graveyards."],
		]),
		_page("Abilities — Alliances combat and adaptations", [
			["Regeneration rewards", "Spiny Starfish counts actual regenerations this turn, not unused shields, and creates that many tokens at the end step. Soldevi Sentry gives its chosen opponent the option to draw only when its shield actually regenerates it."],
			["Prevention and redirection", "Scars of the Veteran prevents up to seven damage; a protected creature later gets one +0/+1 counter for each damage that particular shield prevented. Martyrdom grants a creature you control a repeatable one-point redirection ability for the turn. Only you may activate it, even if the creature changes control. Redirected damage retains its original source; protection and prevention apply to its new recipient."],
			["Upkeep risk", "Thought Lash exiles increasingly many library cards for cumulative upkeep. If you do not pay, it is sacrificed and a separate trigger exiles the rest of your library. Rogue Skycaptain's unpaid wages instead clear its wage counters and pass it to the opponent. Phantasmal Sphere leaves an opposing flying Orb sized by its last counter count."],
			["Extra land plays", "Storm Cauldron grants each player one extra land play each turn. A land tapped for mana returns to its owner's hand through a trigger; the mana is available before that trigger resolves. Lands that require an entry sacrifice demand payment before entering, so a failed payment creates no entry trigger."],
			["Alliances digital adaptations", "Fatal Lore, Library of Lat-Nam and Misfortune let the opponent choose their mode on resolution rather than announcement. Fatal Lore's creature targets are also chosen then, respecting normal targeting restrictions. These differences are printed on the cards and recorded in the simplified-card ledger."],
		]),
		_page("Abilities — Mirage block phasing and flanking", [
			["Phasing", "A permanent with phasing phases out during its controller's untap step, before anything untaps, and phases back in during that player's next untap step. While phased out it is treated as though it does not exist: it cannot be targeted, attack, block, tap for mana or be destroyed, damaged or counted, and it leaves combat. It keeps its counters, its tapped state and its place in play, and Auras on it phase out and back in with it, still attached. Phasing is not leaving or entering the battlefield, so no enters or leaves abilities trigger. Reality Ripple and similar cards phase a permanent out once; it comes back at its controller's next untap step. Nothing phases during a skipped untap step."],
			["What phasing does not change", "A phased-out permanent keeps its controller, its owner and how long it has been on the battlefield, so a creature that phases back in during your untap step can attack that turn if it could before it phased out. Tokens stay tokens. An effect that lasts for as long as the permanent stays somewhere ends when it phases out, and a spell or ability that would affect it while it is phased out does nothing to it."],
			["Phased-out cards on the table", "A phased-out permanent stays on its controller's side of the table, faded and lettered Phased out, for both players to see. Hold the pointer over it to read when it phases back in, or which card holds it out, such as Oubliette, which keeps a creature phased out until Oubliette leaves the battlefield. Clicking it does nothing. Spatial Binding and Ertai's Familiar can stop a permanent phasing out until your next upkeep; such a card says Can't phase out."],
			["Flanking", "Whenever a creature without flanking blocks a creature with flanking, the blocker gets -1/-1 until end of turn. This is a triggered ability on the Spell Chain, so the defender may answer it, for example by pumping the blocker. A blocker it kills dies before combat damage, and the attacker stays blocked; with trample all its damage goes to the player. Each instance triggers separately: Agility on a knight that already has flanking makes two triggers. A creature that loses flanking until end of turn loses every instance."],
		]),
		_page("Abilities — Mirage block flash and costs", [
			["Flash", "A spell with flash can be cast any time you could cast an instant, such as during combat or on your opponent's turn. Several Mirage block cards say you may cast them as though they had flash; if you do so at a time a sorcery could not have been cast, the permanent is sacrificed at the beginning of the next cleanup step, so it lasts for the rest of that turn. Cast in your own main phase with an empty Spell Chain, it stays. Winding Canyons lets you cast creature spells as though they had flash for the rest of the turn. Your hand lights these cards whenever they can be cast, and the duel stops at the fast-effect windows when you could cast one."],
			["The cleanup response window", "The cleanup step usually ends the turn without anyone acting. If a triggered ability begins there, such as a flash-cast Aura's sacrifice or Bounty of the Hunt removing its counters, or a creature dies there, the active player and then the opponent receive priority and the Spell Chain resolves as usual; then another cleanup step follows. The Phase Bar lights its Discard Phase icon meanwhile. With nothing to answer with, the duel passes this window for you."],
			["Cumulative upkeep paid in other ways", "Some cumulative upkeep costs are not mana. Psychic Vortex makes you draw a card for each age counter; Aboroth puts a -1/-1 counter on itself for each. You make the whole payment at once or sacrifice the permanent. When a player does not pay Heart of Bogardan's own cumulative upkeep, its ability triggers; the Heart is sacrificed, and the damage still counts the age counters it had. Other permanents' unpaid upkeep does not trigger it."],
			["Alternative costs and paying with objects", "Fireblast lets you sacrifice two Mountains instead of paying its mana cost, and Spinning Darkness lets you exile the top three black cards of your graveyard; choose the payment when you cast the spell. Other costs return a permanent you control to its owner's hand, exile a card from your hand, or exile the top card of your graveyard, which is always the topmost one that qualifies. Infernal Harvest, Haunting Misery and Firestorm ask for X first; X then counts the objects you give up and costs no mana. You choose the objects as you cast and may still cancel before anything is paid."],
			["Blocking for life", "Heat Wave lets nonblue creatures block your creatures only if their controller pays 1 life for each blocking creature, and blue creatures cannot block them at all. The life is paid when blockers are declared. While you choose blockers the Situation Bar shows what they will cost, and a block you could not pay for is refused."],
		]),
		_page("Abilities — Mirage block digital adaptations", [
			["Regenerating this way", "Debt of Loyalty and Matopi Golem add a consequence when the creature regenerates through them. If the creature also has another regeneration shield, the game uses the plain shield first without asking, and the consequence happens only when their own shield is the one used. That order is always the better one for the creature's controller."],
			["Mind Bend", "Mind Bend works like Magical Hack and Sleight of Mind: it changes one color word or one basic land type word, chosen from a short list, on a permanent that has such a word, such as a protection color, a landwalk, a land type or a basic land's mana. It cannot rewrite other rules text."],
			["Prevention bonuses hit by hit", "Shadowbane gains you life, and Honorable Passage deals damage, separately for each creature or player whose damage the shield prevented, rather than once for the whole event. The total is the same; only an effect that counts each life gain could tell the difference."],
			["Phasing out together", "When several permanents phase out at the same moment, each one notices its own phasing out but not the others', and a permanent phasing in at that moment notices them. Every card in the game that reacts to phasing reacts only to itself, so play is not affected."],
			["Two ways not to die", "If a creature with its own replacement for dying, such as Gravebane Zombie going to the top of its owner's library, would die while Forbidden Crypt is exiling cards headed to your graveyard, the creature's own replacement is applied without asking. That is the order that keeps the card."],
		]),
		_page("Abilities — Tempest block shadow and blocking", [
			["Shadow", "A creature with shadow can block or be blocked only by creatures with shadow. Shadow creatures slip past ordinary blockers, but they cannot block ordinary attackers either. Shadow adds to other evasion: a flying shadow creature can be blocked only by a creature that has shadow and also flying or reach. Blocks are checked only as they are declared, so gaining or losing shadow afterwards does not undo a block. Shadow Rift and Dauthi Embrace give a creature shadow until end of turn; Reality Anchor takes it away."],
			["Blocking creatures with shadow", "Heartwood Dryad and Wall of Diffusion can block creatures with shadow as though they had shadow. They do not have shadow: they still block ordinary attackers, and cards that count or affect creatures with shadow, such as Shadowstorm, pass them by. A creature that is given shadow, by contrast, can block shadow attackers but no longer ordinary ones."],
			["Creatures that must block", "Watchdog blocks each combat if able. Provoke untaps an opposing creature, which must then block this turn if able. Invasion Plans makes every creature block each combat if able and lets the attacking player choose all the blocks. Such a creature must block when it is untapped and there is an attacker it could legally block without any extra cost; its controller still chooses which attacker, unless Invasion Plans hands that choice to the attacking player. Nobody is ever forced to pay to block. A set of blocks that leaves out a creature that could have blocked is refused, and the game names that creature."],
			["Magnetic Web", "Magnetic Web puts magnet counters on creatures, yours or your opponent's, and the counters stay. If a creature with a magnet counter attacks, every other creature with a magnet counter that is able to attack must attack too, so attack with all of your able magnetized creatures or with none of them. When one attacks, a triggered ability also makes every creature with a magnet counter block that attacker this turn if able."],
		]),
		_page("Abilities — Tempest block buyback and casting", [
			["Buyback", "Buyback is an extra cost you may pay as you cast the spell: the game offers the normal payment and the payment with buyback. If the spell resolves, the card returns to your hand instead of your graveyard, ready to cast again. If it is countered, or does nothing because all its targets have become illegal, it goes to the graveyard and the buyback is wasted. Some buyback costs are not mana: Constant Mists sacrifices a land, Forbid discards two cards, Slaughter costs 4 life and Flowstone Flood costs 3 life and a card discarded at random. For a spell with X, such as Fanning the Flames, choose X as usual and pay the buyback on top. Buyback never changes the card's mana value, and a copy of the spell never returns to a hand."],
			["Memory Crystal", "Memory Crystal makes every player's buyback costs two generic mana cheaper. It reduces only the generic mana of the buyback itself, never below zero: never the spell's own cost, never a colored mana symbol, and nothing for a buyback paid with a land, cards or life. Two Crystals take off four. With the 1997 rules a tapped Crystal does nothing, like every tapped artifact's continuous effect."],
			["Casting without paying the mana cost", "Dream Halls lets any player cast a spell by discarding another card that shares a color with it instead of paying its mana cost; a colorless spell cannot be cast this way. Aluren lets any player cast a creature spell with mana value 3 or less without paying its mana cost. Choose the free way when you cast the spell. X counts as zero, extra costs such as buyback must still be paid, and only one way of replacing a mana cost can be used at a time. A spell cast through Dream Halls keeps its usual timing: a sorcery still waits for your main phase."],
			["Casting as though it had flash", "Rootwater Shaman lets its controller cast Aura spells with enchant creature any time they could cast an instant. Aluren gives its free creatures the same timing, but only when they are cast for free through Aluren: paying the mana cost of such a creature still needs the usual timing. Unlike the Mirage block's flash cards, nothing cast this way is sacrificed later."],
			["Mox Diamond", "Whenever Mox Diamond would enter the battlefield, you may discard a land card from your hand. If you do, the Mox enters; if you decline, or have no land card, it goes to your graveyard without ever entering, so nothing notices it arrive. Discarding the land is not playing one, so your land for the turn is still available. The Mox taps for one mana of any color."],
		]),
		_page("Abilities — Tempest block licids, Slivers and Spikes", [
			["Licids", "A licid is a creature with an ability that costs mana and tapping it. The licid then stops being a creature and becomes an Aura attached to the target creature, yours or an opponent's, and the rest of its text works on that creature: Gliding Licid gives flying, Calming Licid stops it attacking, Dominating Licid gives you control of it. Like any tap ability, it needs a licid that has been under your control since your turn began. If the target is no longer legal when the ability resolves, the licid stays a tapped creature. As an Aura it stays tapped, and if the enchanted creature leaves the battlefield, stops being a creature or gains protection from the licid's color, the licid goes to its owner's graveyard, as any Aura would."],
			["Ending a licid's effect", "While a licid is an Aura, the licid's controller may pay the end cost printed on it, such as one red mana for Enraging Licid, whenever they could cast an instant. Paying does not use the Spell Chain and cannot be answered. The licid becomes a creature again where it stands, unattached and still tapped, and it has its licid ability back. Right-click the licid, or your territory, to pay."],
			["Volrath's Curse", "The creature enchanted by Volrath's Curse cannot attack or block, and its activated abilities, mana abilities included, cannot be activated. That creature's controller may sacrifice any permanent they control to ignore the Curse until end of turn, whenever they could cast an instant; the sacrifice does not use the Spell Chain. Right-click the enchanted creature, or your territory, to do it. The Curse's controller may pay one generic and one blue mana to return it to its owner's hand."],
			["Slivers", "Every Sliver gives its ability to every Sliver on the battlefield: your Slivers and your opponent's, itself included. A Sliver that arrives later gets the abilities at once, and they end when the Sliver giving them leaves. A card that names Sliver creatures reaches only Slivers that are creatures; one that names Slivers reaches every permanent with that type. Bonuses add up, so two Muscle Slivers give every Sliver +2/+2. A shared activated ability, such as Clot Sliver's regeneration, belongs to each Sliver: that Sliver's controller pays for it, and it affects only that Sliver. Sliver Queen's tokens are Slivers too."],
			["Spikes", "A Spike is a 0/0 that enters with +1/+1 counters. Its ability costs two generic mana and removing one of its +1/+1 counters, and puts a +1/+1 counter on target creature: another of yours, an opponent's, or the Spike itself. The counter comes off as you activate, before anyone can respond, so a Spike that gives away its last counter dies at once, but the counter it paid for still arrives. Spike Feeder, Spike Weaver and others have further uses for their counters. With the modern rules a +1/+1 and a -1/-1 counter on one creature remove each other; with the 1997 rules both stay and add up."],
		]),
		_page("Abilities — Tempest block notable cards", [
			["Humility", "Humility makes every creature a 1/1 that has lost all its abilities, lands and artifacts that have become creatures included. As on the printed card, effects apply in the order they began: an ability given to a creature after Humility arrived, such as by a Flight attached later or a Jump cast this turn, still works, while one given earlier is removed. A creature's own printed abilities stay off however late it entered. Counters and bonuses still add to the 1/1, so a creature with a +1/+1 counter is 2/2. A size set before Humility arrived gives way to its 1/1, while one set afterwards wins: a Mishra's Factory animated after Humility is a 2/2, though still without abilities."],
			["Volrath's Shapeshifter", "As long as the top card of your graveyard is a creature card, Volrath's Shapeshifter has that card's full text: its name, cost, color, types, abilities, power and toughness, plus the Shapeshifter's own ability to pay two generic mana and discard a card. It changes the moment the top card changes and is itself again when the top card is not a creature. It stays the same permanent: counters, damage and tapping carry over, and no enters ability triggers. If its new toughness cannot bear the damage already marked on it, it dies."],
			["Can't be countered, and Ertai's Meddling", "Scragnoth can't be countered: a counterspell aimed at it does nothing to it. A spell that counters unless its controller pays still asks, and its other effects still happen, so Power Sink still taps the lands of a player who does not pay. Ertai's Meddling does not counter: it exiles target spell with X delay counters, and X can't be 0. At the beginning of each of that spell's controller's upkeeps one counter comes off, and when none are left the card returns to the Spell Chain as the same spell, with the same targets and choices. It is not cast again, and it can be answered like any spell. A target that has changed zones meanwhile is gone. It works on a spell that can't be countered too, and a copy of a spell exiled this way simply ceases to exist."],
			["Static Orb", "While Static Orb is untapped, no player untaps more than two permanents during their untap step; each player chooses which ones when the untap step asks. With Winter Orb also out, at most one of the two may be a land. While the Orb itself is tapped it does nothing."],
			["The Oaths", "The five Exodus Oaths help whoever is behind, and they trigger at the beginning of every player's upkeep, yours and your opponent's. If that player's opponent controls more creatures (Oath of Druids), has fewer creature cards in the graveyard (Oath of Ghouls), controls more lands (Oath of Lieges), has more life (Oath of Mages) or has more cards in hand (Oath of Scholars), the player whose upkeep it is may take the benefit: Druids reveals cards from the top of the library until a creature card, which goes onto the battlefield while the rest go to the graveyard; Ghouls returns a creature card from the graveyard to the hand; Lieges puts a basic land from the library onto the battlefield; Mages deals 1 damage to that opponent; Scholars discards the hand and draws three cards. If the opponent no longer qualifies when the ability resolves, nothing happens."],
			["Pandemonium", "Pandemonium triggers for every creature that enters the battlefield, either player's, tokens included. The entering creature's controller, not Pandemonium's, chooses any target and decides whether the damage is dealt. The creature deals damage equal to its power as the ability resolves, or its last power if it has left by then."],
		]),
		_page("Abilities — Tempest block digital adaptations", [
			["Living Death", "Living Death returns its creatures one after another, the active player's first, rather than all at the same moment. A returned card that reacts when another creature enters, such as Soul Warden, notices only the creatures returned after it."],
			["Skeleton Scavengers", "When Skeleton Scavengers has a regeneration shield from its own ability and another one too, the game uses its own shield first without asking, so it always gets its +1/+1 counter, even though that makes its next regeneration cost one more. Debt of Loyalty and Matopi Golem work the other way round, because their consequence is a loss."],
			["Licids and the order of effects", "A licid that becomes an Aura keeps its place in the order of effects from when it entered the battlefield, instead of taking a new place as it attaches. This matters only if another effect took the same ability away in between: if Radjan Spirit made a creature lose flying after Gliding Licid entered, attaching the Licid to it later that turn does not give flying back. Humility never meets this case, because a licid cannot use its ability while Humility is on the battlefield."],
			["Whim of Volrath", "Whim of Volrath works like Mind Bend, but only until end of turn: it changes one color word or one basic land type word, chosen from a short list, on a permanent that has such a word, such as a protection color, a landwalk, a land type or a basic land's mana. It cannot rewrite other rules text."],
		]),
	]

static func _page(title: String, entries: Array) -> Dictionary:
	var blocks: Array = []
	for entry in entries:
		blocks.append({"kind": "heading", "text": entry[0]})
		blocks.append({"kind": "text", "text": entry[1]})
	return {"title": title, "blocks": blocks}
