extends RefCounted
## The final Help chapter: player-facing rules, not implementation notes.
## Verified against engine/combat.gd, the effect classes, fem/_rules.gd and
## Wizards' Comprehensive Rules (magic.wizards.com/en/rules), especially
## combat, keyword abilities, costs, counters and delayed triggers.
## Keep examples textual so this reference also works with packs disabled.

static func portal_intro() -> Dictionary:
	return _page("Portal — A first step into Magic", [
			["Original Portal, 1997", "Pack 6 adds the original Portal set: straightforward creatures, spells and beautiful basic lands. Enable it in Options → Card Packs, then choose Portal in Deck Builder → Extras. Turn the other sources off to browse its 200 different cards and 215 printings. Select a card, then use the Card variant stone medallion just below the large preview's lower-right corner to choose artwork, including four versions of each basic land. Your saved deck remembers the choice."],
			["Read the current rules", "The original pictures preserve their printed wording. Gameplay uses current card types and rules. Some cards printed as sorceries are now instants. Assassin's Blade, Deep Wood and similar tricks can be cast only after an opponent attacks you, during Declare Attackers — before blockers are declared."],
			["More lands and fewer blockers", "Summer Bloom allows three additional land plays this turn. Charging Rhino and Stalking Tiger cannot be blocked by more than one creature. If such a creature also requires two or more blockers, it cannot be blocked."],
			["Last Chance", "Last Chance grants an extra turn, but you lose at the beginning of that turn's end step. The most recently created extra turn happens first. A normal Time Walk turn does not inherit Last Chance's loss condition."],
			["The large mana symbols", "Portal basic-land previews retain the original printed card and its large mana symbol. Animated lands show the live game frame so their creature statistics remain visible. Saved decks remember one chosen printing per card name."],
		])


static func pages() -> Array:
	return [
		_page("Abilities — Combat", [
			["Flying and reach", "A flying attacker can be blocked only by creatures with flying or reach. Reach does not let a creature fly. Giving flying after blockers are chosen does not remove an existing block."],
			["First strike", "First strikers deal combat damage before creatures without first strike. A creature killed by that early damage does not strike back. First strike does not double the damage."],
			["Trample", "An attacker can assign excess combat damage to the defending player after assigning lethal damage to its blockers. Without trample, an attacker that became blocked normally stays blocked even if its blockers leave."],
			["Vigilance, haste and defender", "Vigilance means attacking does not tap the creature. Haste removes the usual summoning-sickness restriction on attacking and tap-symbol abilities. Defender prevents attacking unless another effect specifically allows it."],
			["Landwalk and menace", "Landwalk makes an attacker unblockable while the defender controls the named land type. Menace means it cannot be blocked by just one creature: the defender needs at least two legal blockers. Goblin War Drums gives this blocking restriction to your creatures."],
		]),
		_page("Abilities — Banding and protection", [
			["Banding when attacking", "You may group creatures with banding and up to one creature without banding into an attacking band. If a creature blocks a member, the whole band becomes blocked. Band members do not share flying, trample or other abilities."],
			["Banding changes damage assignment", "When an attacking band includes banding, its controller chooses how its blockers assign damage among that band. A defending creature with banding similarly lets its controller assign the blocked attacker's damage. Banding does not merge the creatures or their toughness."],
			["Protection", "Protection from a quality prevents damage from matching sources, stops matching Auras from enchanting the creature, stops matching creatures from blocking it, and stops matching spells or abilities from targeting it. Protection from black does not stop every black effect: a non-targeting destroy-all effect can still destroy it."],
			["Shroud", "A permanent with shroud cannot be targeted by either player's spells or abilities, including your own. It can still be affected by effects that do not target. Deep Spawn and Homarid Warrior can gain temporary shroud, but their abilities also tap them and delay their next untap."],
		]),
		_page("Abilities — Costs, triggers and survival", [
			["Activated abilities: cost : effect", "Pay everything before the colon when you activate: mana, tapping, sacrifices, discards or counter removal. Those costs are not returned if the ability is countered or loses its target. A tap-symbol cost needs an untapped source; a summoning-sick creature cannot pay it without haste."],
			["Triggered and static abilities", "When, whenever and at usually introduce triggered abilities. They wait on the Spell Chain and can be answered. Static abilities apply continuously while their conditions hold, without an activation. Mana abilities normally produce mana immediately rather than waiting on the chain."],
			["Regeneration", "Regeneration replaces destruction: tap the creature, remove its marked damage and remove it from combat. It does not return a dead creature. With modern damage timing, create the shield before lethal damage; with classic damage timing, use the regeneration window. Regeneration cannot stop sacrifice, exile, zero toughness or an effect that forbids regeneration."],
			["Counters and temporary boosts", "Counters stay on a permanent until removed or until it leaves the battlefield. A +1/+1 counter changes both stats; +1/+0 and +0/+1 counters change only one. An until-end-of-turn boost expires at cleanup instead. Damage is not a counter and does not reduce the displayed toughness."],
			["Tokens and creature types", "A token is a permanent and follows its creature's normal rules, including summoning sickness. A token that leaves the battlefield cannot later return. Creature types such as Thrull, Goblin, Merfolk and Fungus matter only when a card refers to them; sharing a type does not give creatures shared abilities."],
		]),
		_page("Abilities — Fallen Empires resources", [
			["Spore counters", "Thallids and related creatures gain spore counters during your upkeep. Remove three to pay for the printed ability: making a Saproling, dealing damage, preventing combat damage or regenerating. Spore counters alone do not increase power or toughness. Fungal Bloom adds a spore counter to a Fungus."],
			["Storage lands", "These lands enter tapped. You may leave one tapped during your untap step, and it gains a storage counter during your upkeep if it is tapped. Once untapped, use its mana ability and remove the chosen number of storage counters to produce that much mana."],
			["Mana conversion and High Tide", "Initiates of the Ebon Hand and Farrelite Priest turn one mana into the printed color without tapping. Using one at least four times in a turn creates a sacrifice trigger for the next end step. Implements of Sacrifice costs one mana, tapping and sacrificing itself to make two mana of one color. High Tide adds blue mana when an Island is tapped for mana that turn."],
			["Tide, net, time and credit counters", "Homarid and Tidal Influence change their effects as tide counters rise, then reset. Merseine's net counters keep its host from untapping; the host's controller may pay to remove them. Tourach's Gate consumes time counters at upkeep. Icatian Moneychanger stores credit counters that its sacrifice ability turns into life."],
		]),
		_page("Abilities — Fallen Empires combat tricks", [
			["Sacrifices and crew taps", "Goblin Warrens sacrifices two Goblins to make three. Night Soil exiles two creature cards from one graveyard to make a Saproling. War Machine and Hand of Justice require other creatures to tap as costs. A cost that says to tap an eligible creature is different from that creature paying its own tap symbol, so newly arrived helpers can be used."],
			["Unblocked-attack abilities", "Farrel's Zealot, Farrel's Mantle, Mindstab Thrull and Necrite trigger after blockers are declared if their attacker is unblocked. Delif's artifacts first set up a delayed trigger. Read whether the card replaces combat-damage assignment, prevents damage, or sacrifices the attacker: these are different effects."],
			["Effects that last while a condition holds", "Seasinger's control lasts while it remains tapped and under your control; Thrull Champion also needs you to keep control of the Champion. Spirit Shield and Zelyon Sword maintain their bonuses while tapped. Untapping or losing the required control ends the effect; tapping or taking the source back does not restart it."],
			["Coin flips and delayed effects", "Goblin Kites grants flying now, then flips a coin at the next end step; losing means sacrificing that creature if you still control it. Orcish Captain flips for a bonus or penalty. These are genuine random outcomes. Rainbow Vale gives its mana now and changes control through a later end-step trigger."],
			["New objects, not returned effects", "A card that leaves the battlefield and returns is a new permanent. Old counters, temporary effects and abilities waiting to affect its previous incarnation do not automatically follow it back. An ability already on the Spell Chain can still resolve even if its source leaves."],
		]),
		_page("Abilities — Ice Age resources", [
			["Snow lands", "Snow is a supertype, not a sixth mana color. Snow-Covered Island is still a basic Island and makes blue mana. A card counts snow lands only when its instructions say so. Snow landwalk checks the defending player's snow land of the named type."],
			["Cumulative upkeep", "At the beginning of your upkeep, put an age counter on that permanent. Then pay its upkeep cost once for each age counter, or sacrifice it. The whole payment is optional but must be paid in full. Multiple cumulative-upkeep abilities trigger separately and use the same age counters. Sacrifice cannot be regenerated."],
			["Restricted mana", "Adarkar Unicorn and Snowfall can produce mana usable only for cumulative upkeep. Soldevi Machinist's mana is only for activated abilities of artifacts, not for casting artifact spells. The game keeps restricted mana separate and checks what you are paying for."],
			["Delayed card draws", "Many Ice Age spells draw at the beginning of the next turn's upkeep, not immediately. The draw is already scheduled even if its source leaves play. If every target of the original spell becomes illegal, that spell does not resolve and does not schedule its draw."],
			["Wind counters and one-time abilities", "Freyalise's Winds adds a counter when a permanent becomes tapped. During its controller's untap step, removing all wind counters replaces untapping it. Other untap effects still work normally. Goblin Ski Patrol says activate only once: countering that activation does not restore the use. Leaving and returning creates a new object."],
		]),
		_page("Abilities — Ice Age zones and control", [
			["Abilities in the graveyard", "Most abilities work only on the battlefield. Ashen Ghoul and Whiteout explicitly let you activate from your graveyard; their timing and costs still apply. A graveyard ability on the Spell Chain does not give every other card in that graveyard permission to act."],
			["Playing cards from exile", "Exile does not normally let you play a card. Elkin Bottle and Ice Cauldron give permission for the particular exiled card. Normal costs and timing still apply, including the land-per-turn limit. Face-down exiled cards stay hidden unless an effect lets a player look at them."],
			["Storing mana", "Jeweled Amulet remembers the mana type actually paid to charge it. Ice Cauldron remembers the amounts and types paid and releases mana usable only for its last exiled card. Removing the artifact does not cancel the permission to cast a card already exiled with it."],
			["Borrowing and holding permanents", "Ray of Command and Magus of the Unseen borrow until end of turn and later tap the returned permanent through a trigger. Merieke's control ends when you lose control of Merieke, but her destruction trigger waits until she untaps or leaves. A newer control effect can override an older one; ending it reveals any older effect that is still valid."],
			["Claims on dead creatures", "Krovikan Vampire checks at each end step for creatures it damaged that died that turn. Seraph first triggers when a damaged creature dies, then schedules the return. The card must remain in that graveyard. Leaving and returning makes a new object: old damage and old claims do not follow a fresh incarnation."],
		]),
		_page("Abilities — Ice Age combat and adaptations", [
			["Attacking and blocking costs", "Orcish Conscripts needs at least two other attacking creatures to attack, or two other blocking creatures to block. Errantry's host can attack only alone. Flooded Woodlands and Reclamation charge land sacrifices to attack with the named color; you may decline to attack instead. Hipparion charges mana to block a creature with power 3 or greater."],
			["Melee and General Jarkeld", "Melee lets the attacker choose the defender's blocks for that combat; the defender still decides whether to pay any blocking costs. Unblocked attackers are untapped and removed from combat through triggered abilities. General Jarkeld exchanges the blockers of two blocked attackers only if the new blocks are legal."],
			["Gaze of Pain", "Each unblocked attacker gets a targeted trigger. You may have that creature deal damage equal to its power to the target creature; if you do, it assigns no combat damage that turn. This is not combat damage, and a creature that was blocked does not qualify just because its blocker later leaves."],
			["Drought and Soul Burn", "Drought adds Swamp sacrifices for each printed black mana symbol in a spell's cost or an ability's activation cost. Soul Burn's X is not extra black symbols: it accepts only actual black or red mana. Cost reductions can reduce what you pay for X without reducing X's damage; life gain counts only black mana actually spent on X and is capped by the damage and the victim's life or toughness."],
			["Documented digital adaptations", "Balduvian Shaman changes a color only on one of the five colored Circles of Protection you control; it cannot rewrite arbitrary enchantment text. It still grants cumulative upkeep. Game of Chaos stops after 30 flips in one resolution. These differences are also printed on the digital cards."],
		]),
		_page("Abilities — Homelands resources and locks", [
			["Finite counters", "Serrated Arrows starts with three arrowheads; removing one pays for a -1/-1 counter on a creature. At your upkeep, an empty Arrows is sacrificed. Clockwork Steed and Swarm lose a +1/+0 counter at end of combat after participating; their X-and-tap ability recharges only during your upkeep, to at most four counters."],
			["Giant Oyster", "Target a tapped creature. While the Oyster remains tapped, that creature skips normal untapping and receives a -1/-1 counter in each of your draw steps. Untapping or removing the Oyster ends the lock and triggers removal of all -1/-1 counters on that creature. Tapping the Oyster again does not restart the old effect."],
			["Putting cards into play", "Didgeridoo and Willow Priestess put eligible cards from your hand directly onto the battlefield. This is not casting a spell, so Aether Storm does not stop it. Ordinary entry triggers and summoning sickness still apply. Any player may pay four life to activate Aether Storm's destruction ability."],
			["Taxes and untap restrictions", "Koskun Falls charges two mana for each creature attacking its controller. Paying for one attacker does not pay for the rest. Some cards say your next untap step, while others refer to the affected creature's next normal untap. Changing control does not turn those phrases into the same instruction."],
		]),
		_page("Abilities — Homelands combat and ownership", [
			["Damage redirection", "Hazduhr the Abbot redirects up to the chosen X damage from a white creature you control to himself. Daughter of Autumn redirects the next one damage from any target white creature. Damage keeps its original source and combat status. Protection and prevention still apply to its new recipient; redirection is not a toughness bonus."],
			["Shroud permission", "Autumn Willow has shroud. Her green-mana ability gives the chosen player permission to target her for that turn; it does not remove shroud for everyone. Effects that do not target need no such permission."],
			["Badger and graveyard targets", "Rysorian Badger may target up to two creature cards in the defending player's graveyard when it attacks unblocked. Exiling them gains one life per card actually exiled, but the Badger then assigns no combat damage that turn. You can choose zero targets or decline the exchange."],
			["Ownership and the digital adaptation", "Timmerian Fiends lets the artifact's owner ante the top card of their library instead of exchanging ownership. Otherwise both cards go to their new owners' graveyards, even if the Fiends has moved elsewhere. Ownership differs from battlefield control. Digital adaptation: token copies cannot participate in this exchange; the restriction is also printed on the card and listed in the simplified-card ledger."],
		]),
		_page("Abilities — Alliances costs and resources", [
			["Pitch spells", "Force of Will, Pyrokinesis, Contagion, Bounty of the Hunt and Scars of the Veteran offer an alternative to their mana cost: exile another card of the required color from your hand. Force of Will and Contagion also cost one life. Choose the payment mode before targets and payment; extra taxes still apply. Their printed mana values do not become zero."],
			["Mana from your hand", "Elvish Spirit Guide can be exiled from your hand to add one green mana without using the Spell Chain. Its ability does not work from the battlefield. It cannot pay for casting itself."],
			["Library and object costs", "Some abilities exile cards from the top of your library as a cost, before anyone can respond. You need enough cards to pay. Viscerid Drone needs both a creature and a separate Swamp; its snow-Swamp ability can also destroy artifact creatures. A tap-enchanted-creature cost is not a tap-symbol ability of that creature, so summoning sickness does not stop it."],
			["Variable and repeated costs", "Gorilla Shaman pays twice X plus one to destroy a noncreature artifact whose mana value is X. Primitive Justice pays an extra one generic plus red or green for each additional artifact target; green payments also gain life. Taste of Paradise lets you pay one generic and one green repeatedly for three extra life each time."],
			["Hidden piles and linked cards", "Phyrexian Portal lets the opponent inspect ten cards and split them; the library's owner chooses which pile to exile without seeing its cards. Gustha's Scepter exiles a hand card face down and only its controller at that time may inspect it. Losing control of the Scepter or removing it sends its linked cards to their owners' graveyards."],
		]),
		_page("Abilities — Alliances combat and adaptations", [
			["Regeneration rewards", "Spiny Starfish counts actual regenerations this turn, not unused shields, and creates that many tokens at the end step. Soldevi Sentry gives its chosen opponent the option to draw only when its shield actually regenerates it."],
			["Prevention and redirection", "Scars of the Veteran prevents up to seven damage; a protected creature later gets one +0/+1 counter for each damage that particular shield prevented. Martyrdom grants a creature you control a repeatable one-point redirection ability for the turn. Only you may activate it, even if the creature changes control. Redirected damage retains its original source; protection and prevention apply to its new recipient."],
			["Upkeep risk", "Thought Lash exiles increasingly many library cards for cumulative upkeep. If you do not pay, it is sacrificed and a separate trigger exiles the rest of your library. Rogue Skycaptain's unpaid wages instead clear its wage counters and pass it to the opponent. Phantasmal Sphere leaves an opposing flying Orb sized by its last counter count."],
			["Extra land plays", "Storm Cauldron grants each player one extra land play each turn. A land tapped for mana returns to its owner's hand through a trigger; the mana is available before that trigger resolves. Lands that require an entry sacrifice demand payment before entering, so a failed payment creates no entry trigger."],
			["Alliances digital adaptations", "Fatal Lore, Library of Lat-Nam and Misfortune let the opponent choose their mode on resolution rather than announcement. Fatal Lore's creature targets are also chosen then, respecting normal targeting restrictions. Bounty of the Hunt removes its counters and Thawing Glaciers returns at cleanup, but the game does not open a response window for those cleanup actions. These differences are printed on the cards and recorded in the simplified-card ledger."],
		]),
	]

static func _page(title: String, entries: Array) -> Dictionary:
	var blocks: Array = []
	for entry in entries:
		blocks.append({"kind": "heading", "text": entry[0]})
		blocks.append({"kind": "text", "text": entry[1]})
	return {"title": title, "blocks": blocks}
