extends CardScript
## Knights of Thorn — {3}{W} — Creature — Human Knight — 2/2 — (drk, rare)
## Oracle: Protection from red; banding (Any creatures with banding, and up to one without, can attack in a band. Bands are blocked as a group. If any creatures with banding you control are blocking or being blocked by a creature, you divide that creature's combat damage, not its controller, among any of the creatures it's being blocked by or is blocking.)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Knights of Thorn", "{3}{W}", Mtg.CardType.CREATURE) \
		.pt(2, 2) \
		.with_subtypes(["human", "knight"]) \
		.with_keywords([Mtg.Keyword.BANDING]) \
		.with_protection_from(Mtg.ManaColor.R) \
		.oracle("Protection from red; banding (Any creatures with banding, and up to one without, can attack in a band. Bands are blocked as a group. If any creatures with banding you control are blocking or being blocked by a creature, you divide that creature's combat damage, not its controller, among any of the creatures it's being blocked by or is blocking.)")
