extends CardScript
## Marsh Goblins — {B}{R} — Creature — Goblin — 1/1 — (drk, common)
## Oracle: Swampwalk (This creature can't be blocked as long as defending player controls a Swamp.)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Marsh Goblins", "{B}{R}", Mtg.CardType.CREATURE) \
		.pt(1, 1) \
		.with_subtypes(["goblin"]) \
		.with_landwalk(["swamp"]) \
		.oracle("Swampwalk (This creature can't be blocked as long as defending player controls a Swamp.)")
