extends CardScript
## Scarwood Goblins — {R}{G} — Creature — Goblin — 2/2 — (drk, common)
## Oracle: (no rules text — vanilla creature)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Scarwood Goblins", "{R}{G}", Mtg.CardType.CREATURE) \
		.pt(2, 2) \
		.with_subtypes(["goblin"]) \
		.oracle("")
