extends CardScript
## Squire — {1}{W} — Creature — Human Soldier — 1/2 — (drk, common)
## Oracle: (no rules text — vanilla creature)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Squire", "{1}{W}", Mtg.CardType.CREATURE) \
		.pt(1, 2) \
		.with_subtypes(["human", "soldier"]) \
		.oracle("")
