#!/usr/bin/env python3
"""Generate GDScript card files from cards/data/<set>.json (our port of
mage-go's `genset` idea, in this project's one-card-per-file style).

What it does, per set, in pool order (2ed, 4ed, arn, atq, leg, drk, past,
phpr — first printing wins, reprints in later sets are skipped):

1. Deduplicates by card name (within and across sets) and skips any card
   already implemented by hand under cards/sets/ (scanned by CardData.new
   name, so regeneration never clobbers hand-written work).
2. AUTO-IMPLEMENTS the safely mechanical subset directly into
   cards/sets/<set>/: creatures (incl. artifact/legendary creatures) whose
   oracle text is empty or consists only of keywords the engine supports
   (flying, trample, vigilance, haste, reach, defender), with integer P/T.
   These are marked AUTOGENERATED; re-running regenerates them in place.
3. Writes documented TODO STUBS for everything else into cards/todo/<set>/
   (NOT scanned by the registry). Implementing a card = writing its test,
   filling in build(), and MOVING the file to cards/sets/<set>/ — see
   docs/adding-cards.md.

Idempotent: safe to re-run after refreshing data with fetch_cards.py.
Hand-written files (no AUTOGENERATED marker) are never touched.
"""

import json
import re
import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "cards" / "data"
SETS_DIR = ROOT / "cards" / "sets"
TODO_DIR = ROOT / "cards" / "todo"

# Pool order = dedupe priority (first printing wins).
POOL = ["2ed", "4ed", "arn", "atq", "leg", "drk", "past", "phpr"]

SUPPORTED_KEYWORDS = {
    "flying": "Mtg.Keyword.FLYING",
    "trample": "Mtg.Keyword.TRAMPLE",
    "vigilance": "Mtg.Keyword.VIGILANCE",
    "haste": "Mtg.Keyword.HASTE",
    "reach": "Mtg.Keyword.REACH",
    "defender": "Mtg.Keyword.DEFENDER",
    "first strike": "Mtg.Keyword.FIRST_STRIKE",
    "banding": "Mtg.Keyword.BANDING",
}

# Parameterized abilities the engine supports as data fields.
PROTECTION_COLORS = {"white": "W", "blue": "U", "black": "B",
                     "red": "R", "green": "G"}
LANDWALKS = {"plainswalk": "plains", "islandwalk": "island",
             "swampwalk": "swamp", "mountainwalk": "mountain",
             "forestwalk": "forest"}

TYPE_FLAGS = {
    "Land": "Mtg.CardType.LAND",
    "Creature": "Mtg.CardType.CREATURE",
    "Artifact": "Mtg.CardType.ARTIFACT",
    "Enchantment": "Mtg.CardType.ENCHANTMENT",
    "Instant": "Mtg.CardType.INSTANT",
    "Sorcery": "Mtg.CardType.SORCERY",
}
SUPERTYPE_FLAGS = {"Basic": "Mtg.Supertype.BASIC", "Legendary": "Mtg.Supertype.LEGENDARY"}

AUTOGEN_MARKER = "## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line."


def slugify(name: str) -> str:
    ascii_name = unicodedata.normalize("NFKD", name).encode("ascii", "ignore").decode()
    slug = re.sub(r"[^a-z0-9]+", "_", ascii_name.lower()).strip("_")
    return slug or "card"


def gd_string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def existing_hand_written_names() -> set[str]:
    """Card names defined by non-autogenerated files under cards/sets/."""
    names: set[str] = set()
    for path in SETS_DIR.rglob("*.gd"):
        text = path.read_text(encoding="utf-8")
        if AUTOGEN_MARKER in text:
            continue
        for m in re.finditer(r'CardData\.new\("((?:[^"\\]|\\.)*)"', text):
            names.add(m.group(1).replace('\\"', '"'))
    return names


def parse_type_line(type_line: str):
    """-> (types_expr, supertypes_expr_or_None, subtypes list)."""
    left, _, right = type_line.partition("—")
    words = left.split()
    types = [TYPE_FLAGS[w] for w in words if w in TYPE_FLAGS]
    supers = [SUPERTYPE_FLAGS[w] for w in words if w in SUPERTYPE_FLAGS]
    subtypes = [s.lower() for s in right.split()]
    return " | ".join(types) or "0", " | ".join(supers) or None, subtypes


def strip_reminder(oracle: str) -> str:
    return re.sub(r"\([^)]*\)", "", oracle or "").strip()


def keyword_only(oracle: str):
    """If oracle text is only supported abilities, return a dict of
    {keywords, protection, landwalk} builder inputs; None otherwise."""
    stripped = strip_reminder(oracle)
    result = {"keywords": [], "protection": [], "landwalk": []}
    if not stripped:
        return result
    for token in re.split(r"[,;\n]", stripped):
        token = token.strip().lower()
        if not token:
            continue
        if token in SUPPORTED_KEYWORDS:
            result["keywords"].append(SUPPORTED_KEYWORDS[token])
        elif token.startswith("protection from ") \
                and token.removeprefix("protection from ") in PROTECTION_COLORS:
            result["protection"].append(
                "Mtg.ManaColor." + PROTECTION_COLORS[token.removeprefix("protection from ")])
        elif token in LANDWALKS:
            result["landwalk"].append(LANDWALKS[token])
        else:
            return None
    return result


def is_auto_implementable(card: dict) -> bool:
    types = (card.get("type_line") or "").partition("—")[0]
    if "Creature" not in types:
        return False
    power, toughness = card.get("power"), card.get("toughness")
    if not (power and toughness and power.isdigit() and toughness.isdigit()):
        return False
    return keyword_only(card.get("oracle_text")) is not None


def doc_header(card: dict, set_code: str) -> str:
    """The card file's documentation block, house style."""
    bits = [card["name"]]
    if card.get("mana_cost"):
        bits.append(card["mana_cost"])
    bits.append(card.get("type_line", ""))
    if card.get("power") is not None:
        bits.append("%s/%s" % (card["power"], card["toughness"]))
    bits.append("(%s, %s)" % (set_code, card.get("rarity", "?")))
    lines = ["## " + " — ".join(bits)]
    oracle = card.get("oracle_text") or ""
    if oracle:
        first = True
        for line in oracle.split("\n"):
            # keep long oracle lines intact; they are documentation
            prefix = "## Oracle: " if first else "##         "
            lines.append(prefix + line)
            first = False
    else:
        lines.append("## Oracle: (no rules text — vanilla creature)")
    return "\n".join(lines)


def render_auto(card: dict, set_code: str) -> str:
    types_expr, supers_expr, subtypes = parse_type_line(card["type_line"])
    parsed = keyword_only(card.get("oracle_text"))
    b = ["\treturn CardData.new(%s, %s, %s)" % (
        gd_string(card["name"]), gd_string(card.get("mana_cost") or ""), types_expr)]
    b.append("\t\t.pt(%s, %s)" % (card["power"], card["toughness"]))
    if supers_expr:
        b.append("\t\t.with_supertypes(%s)" % supers_expr)
    if subtypes:
        b.append("\t\t.with_subtypes([%s])" % ", ".join(gd_string(s) for s in subtypes))
    if parsed["keywords"]:
        b.append("\t\t.with_keywords([%s])" % ", ".join(parsed["keywords"]))
    if parsed["protection"]:
        b.append("\t\t.with_protection_from(%s)" % " | ".join(parsed["protection"]))
    if parsed["landwalk"]:
        b.append("\t\t.with_landwalk([%s])" % ", ".join(gd_string(w) for w in parsed["landwalk"]))
    b.append("\t\t.oracle(%s)" % gd_string(card.get("oracle_text") or ""))
    body = " \\\n".join(b)
    return "\n".join([
        "extends CardScript",
        doc_header(card, set_code),
        "##",
        "## Stats-and-keywords card generated from Scryfall data.",
        AUTOGEN_MARKER,
        "",
        "",
        "func build() -> CardData:",
        body,
        "",
    ])


def render_stub(card: dict, set_code: str) -> str:
    return "\n".join([
        "extends CardScript",
        doc_header(card, set_code),
        "##",
        "## STATUS: TODO — not implemented. This stub is NOT loaded (cards/todo/",
        "## is outside the registry scan). To implement: write the test first,",
        "## fill in build(), move this file to cards/sets/%s/ and update the" % set_code,
        "## set count test. Full guide: docs/adding-cards.md.",
        AUTOGEN_MARKER,
        "",
        "",
        "func build() -> CardData:",
        '\tpush_error("TODO card not implemented: %s")' % card["name"],
        "\treturn null",
        "",
    ])


def main() -> int:
    hand_written = existing_hand_written_names()
    seen: set[str] = set(hand_written)
    auto_written: set[str] = set()
    stats = {}
    for set_code in POOL:
        data = json.loads((DATA_DIR / f"{set_code}.json").read_text(encoding="utf-8"))
        auto_dir = SETS_DIR / set_code
        todo_dir = TODO_DIR / set_code
        n_auto = n_todo = n_dupe = 0
        for card in data:
            name = card["name"]
            if name in seen:
                n_dupe += 1
                continue
            seen.add(name)
            slug = slugify(name) + ".gd"
            if is_auto_implementable(card):
                auto_dir.mkdir(parents=True, exist_ok=True)
                (auto_dir / slug).write_text(render_auto(card, set_code), encoding="utf-8")
                auto_written.add(name)
                n_auto += 1
            else:
                todo_dir.mkdir(parents=True, exist_ok=True)
                (todo_dir / slug).write_text(render_stub(card, set_code), encoding="utf-8")
                n_todo += 1
        stats[set_code] = (n_auto, n_todo, n_dupe)
        print(f"{set_code}: auto-implemented {n_auto}, todo stubs {n_todo}, "
              f"skipped (reprint/hand-written) {n_dupe}")

    # Stale-stub cleanup: a stub whose card has since been implemented
    # (hand-written in cards/sets/, or auto-implemented by a NEWER version
    # of this generator than the one that stubbed it) must not linger in
    # todo/ — graduating normally deletes it by hand; this catches misses.
    removed = 0
    for stub in TODO_DIR.rglob("*.gd"):
        text = stub.read_text(encoding="utf-8")
        m = re.search(r'TODO card not implemented: (.+?)"', text)
        if m and (m.group(1) in hand_written or m.group(1) in auto_written):
            stub.unlink()
            # a companion .uid (Godot resource id) is stale with it
            uid = stub.with_suffix(stub.suffix + ".uid")
            if uid.exists():
                uid.unlink()
            removed += 1
    if removed:
        print(f"cleaned {removed} stale stub(s) for graduated cards")
    total_auto = sum(s[0] for s in stats.values())
    total_todo = sum(s[1] for s in stats.values())
    print(f"\npool: {len(seen) - len(hand_written)} generated names "
          f"(+{len(hand_written)} hand-written) — "
          f"{total_auto} auto, {total_todo} stubs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
