"""Offline checks for the dedicated Fifth Edition construction tool."""
import base64
import tempfile
import subprocess
import unittest
import warnings
from unittest.mock import patch
import zipfile
from pathlib import Path

import pack_7_fifth_edition as pack
import pack_1_dotp_complete as first
import fetch_card_art

class PackSevenTests(unittest.TestCase):
    # A real one-pixel JPEG, generated by Godot; no downloaded card art.
    JPEG = base64.b64decode('/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAABAAEDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDmqKKK5zlP/9k=')
    def test_release_guard_refuses_each_numbered_pack_but_allows_source(self):
        source = (pack.ROOT / 'build_release.sh').read_text(encoding='utf-8')
        guard = 'guard_stage() {' + source.split('guard_stage() {', 1)[1].split('\n}\n', 1)[0] + '\n}\n'
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            (root / 'pack_7_fifth_edition.py').write_text('# construction source\n')
            def check():
                return subprocess.run(['bash', '-c', guard + 'guard_stage "$1"', 'guard-test', str(root)],
                                      capture_output=True, text=True)
            self.assertEqual(check().returncode, 0)
            for filename in ['Pack-1-DotP-complete.zip', 'Pack-2-Fallen-Empires.zip', 'Pack-3-Ice_Age.zip', 'Pack-4-Homelands.zip', 'Pack-6-Portal.zip', pack.FILE_NAME]:
                archive = root / filename
                archive.write_bytes(b'local only')
                result = check()
                self.assertNotEqual(result.returncode, 0)
                self.assertIn('local artifacts', result.stderr)
                archive.unlink()

    def test_full_checklist_is_entirely_reprints(self):
        manifest, catalog, cards, _ = pack.assembled()
        names = {row['name'] for row in cards}
        self.assertEqual(len(names), 434)
        self.assertEqual(len(cards), 449)
        self.assertEqual(set(catalog['sets']), {'5ed'})
        self.assertEqual(len(catalog['sets']['5ed']['names']), 434)
        self.assertEqual(set(catalog['sets']['5ed']['names']), names)
        self.assertEqual({row['collector_number'] for row in cards}, {str(n) for n in range(1, 450)})
        core = {name for _, name in first.assigned_pairs()}
        expansions = {}
        for path in sorted((pack.ROOT / 'packaging/card_packs').glob('*/cards*.json')):
            if path.parent == pack.SOURCE or path.parent.name == 'pack_1_dotp_complete':
                continue
            for row in pack.read_json(path):
                expansions.setdefault(row['name'], set()).add(row['set'])
        self.assertEqual(names & core, names - set(pack.shared_names()))
        self.assertEqual(len(names & core), 287)
        self.assertEqual(names, set(pack.read_json(pack.SOURCE / 'reprint_names.json')))
        self.assertEqual(manifest['new_rules_identities'], [])
        self.assertEqual(manifest['counts'], {'published_printings': 449, 'named_set_entries': 434,
            'distinct_cards': 434, 'pack_card_entries': 449, 'reprint_entries': 434, 'new_rules_identities': 0})
        self.assertEqual(manifest['id'], 'pack-7')
        # The shared names are exactly the reprints from Packs 2-4, each keyed
        # to the earliest expansion that printed it, with its script present.
        shared = pack.read_json(pack.SOURCE / pack.SHARED_NAMES_FILE)
        self.assertEqual(set(shared), names - core)
        self.assertEqual(len(shared), 147)
        order = ['fem', 'ice', 'hml']
        for name, code in shared.items():
            self.assertIn(code, order)
            printed = [c for c in order if c in expansions[name]]
            self.assertEqual(code, printed[0], name)
            self.assertTrue((pack.ROOT / 'cards/sets' / code / (fetch_card_art.snake(name) + '.gd')).is_file(), name)
        self.assertEqual(sorted(shared.values()).count('ice'), 89)
        self.assertEqual(sorted(shared.values()).count('hml'), 29)
        self.assertEqual(sorted(shared.values()).count('fem'), 29)
        self.assertEqual(len(pack.art_targets(Path('unused'))), 898)
        self.assertEqual(len({str(path) for path, _, _ in pack.art_targets(Path('unused'))}), 898)
        for land, numbers in [('Plains', ['430', '431', '432', '433']), ('Forest', ['446', '447', '448', '449'])]:
            self.assertEqual([row['collector_number'] for row in cards if row['name'] == land], numbers)
        multiple = {row['name'] for row in cards} - {row['name'] for row in cards if sum(1 for r in cards if r['name'] == row['name']) == 1}
        self.assertEqual(multiple, {'Plains', 'Island', 'Swamp', 'Mountain', 'Forest'})
        self.assertNotIn('Serra Angel', names)

    def test_deterministic_art_archive_and_no_scripts(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            for path, _, _ in pack.art_targets(root / 'art'):
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(self.JPEG)
            out = root / pack.FILE_NAME
            again = root / 'again' / pack.FILE_NAME
            pack.build(out, root / 'art')
            pack.build(again, root / 'art')
            self.assertEqual(out.read_bytes(), again.read_bytes())
            self.assertEqual(pack.verify(out)['checksums']['artwork']['files'], 1192)
            with zipfile.ZipFile(out) as archive:
                self.assertEqual(len(archive.namelist()), 1196)
                self.assertFalse(any(name.endswith('.gd') for name in archive.namelist()))
                shared = pack.shared_names()
                for name in pack.read_json(pack.SOURCE / 'reprint_names.json'):
                    stem = 'skin/cardart/' + fetch_card_art.snake(name)
                    if name in shared:
                        self.assertIn(stem + '.jpg', archive.namelist())
                        self.assertIn(stem + '_card.jpg', archive.namelist())
                    else:
                        self.assertNotIn(stem + '.jpg', archive.namelist())
                self.assertIn(pack.PREFIX + 'art/5ed/forest__447.jpg', archive.namelist())
                self.assertNotIn('skin/cardart/forest.jpg', archive.namelist())

    def test_metadata_only_is_not_a_player_pack(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / pack.FILE_NAME
            pack.build(out, include_art=False)
            pack.verify(out, require_art=False)
            with self.assertRaises(ValueError):
                pack.verify(out)

    def test_extra_and_duplicate_entries_are_refused(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / pack.FILE_NAME
            pack.build(out, include_art=False)
            with zipfile.ZipFile(out, 'a') as archive:
                archive.writestr('injected.gd', 'extends Node')
            with self.assertRaisesRegex(ValueError, 'unexpected'):
                pack.verify(out, require_art=False)
            pack.build(out, include_art=False)
            with warnings.catch_warnings():
                warnings.simplefilter('ignore', UserWarning)
                with zipfile.ZipFile(out, 'a') as archive:
                    archive.writestr(pack.PREFIX + 'README.txt', 'duplicate')
            with self.assertRaisesRegex(ValueError, 'duplicate'):
                pack.verify(out, require_art=False)

    def test_failed_verification_does_not_replace_previous_pack(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / pack.FILE_NAME
            pack.build(out, include_art=False)
            before = out.read_bytes()
            with patch.object(pack, 'verify', side_effect=ValueError('test failure')):
                with self.assertRaises(ValueError):
                    pack.build(out, include_art=False)
            self.assertEqual(out.read_bytes(), before)
            self.assertEqual(list(out.parent.iterdir()), [out])

    def test_uncompressed_size_is_bounded_before_reading_members(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / pack.FILE_NAME
            with zipfile.ZipFile(out, 'w', compression=zipfile.ZIP_DEFLATED) as archive:
                archive.writestr(pack.PREFIX + 'README.txt', b'x' * (8 * 1024 * 1024 + 1))
            with self.assertRaisesRegex(ValueError, 'size limits'):
                pack.verify(out)

    def test_metadata_tampering_is_rejected(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / pack.FILE_NAME
            pack.build(out, include_art=False)
            with zipfile.ZipFile(out) as archive:
                files = {name: archive.read(name) for name in archive.namelist()}
            files[pack.PREFIX + 'README.txt'] = b'changed'
            with zipfile.ZipFile(out, 'w') as archive:
                for name, value in files.items(): archive.writestr(name, value)
            with self.assertRaisesRegex(ValueError, 'trusted source'):
                pack.verify(out, require_art=False)

if __name__ == '__main__':
    unittest.main()
