"""Offline checks for the dedicated Mirage block construction tool."""
import base64
import tempfile
import subprocess
import unittest
import warnings
from unittest.mock import patch
import zipfile
from pathlib import Path

import pack_8_mirage_block as pack
import pack_1_dotp_complete as first
import fetch_card_art

class PackEightTests(unittest.TestCase):
    # A real one-pixel JPEG, generated by Godot; no downloaded card art.
    JPEG = base64.b64decode('/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAABAAEDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDmqKKK5zlP/9k=')
    def test_release_guard_refuses_each_numbered_pack_but_allows_source(self):
        source = (pack.ROOT / 'build_release.sh').read_text(encoding='utf-8')
        guard = 'guard_stage() {' + source.split('guard_stage() {', 1)[1].split('\n}\n', 1)[0] + '\n}\n'
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            (root / 'pack_8_mirage_block.py').write_text('# construction source\n')
            def check():
                return subprocess.run(['bash', '-c', guard + 'guard_stage "$1"', 'guard-test', str(root)],
                                      capture_output=True, text=True)
            self.assertEqual(check().returncode, 0)
            for filename in ['Pack-1-DotP-complete.zip', 'Pack-6-Portal.zip', 'Pack-7-Fifth-Edition.zip', pack.FILE_NAME]:
                archive = root / filename
                archive.write_bytes(b'local only')
                result = check()
                self.assertNotEqual(result.returncode, 0)
                self.assertIn('local artifacts', result.stderr)
                archive.unlink()

    def test_three_sets_checklist_reprints_and_new_identities(self):
        manifest, catalog, cards, _ = pack.assembled()
        names = {row['name'] for row in cards}
        self.assertEqual(len(cards), 684)
        self.assertEqual(len(names), 669)
        self.assertEqual(list(catalog['sets']), ['mir', 'vis', 'wth'])
        self.assertEqual(manifest['set_order'], ['mir', 'vis', 'wth'])
        for code, (printings, named) in pack.SETS.items():
            rows = [row for row in cards if row['set'] == code]
            self.assertEqual(len(rows), printings, code)
            self.assertEqual(len(catalog['sets'][code]['names']), named, code)
            self.assertEqual({row['collector_number'] for row in rows}, {str(n) for n in range(1, printings + 1)}, code)
        self.assertEqual((len(pack.read_json(pack.SOURCE / 'cards.json')),
                          len(pack.read_json(pack.SOURCE / 'cards_vis.json')),
                          len(pack.read_json(pack.SOURCE / 'cards_wth.json'))), (350, 167, 167))
        # No name repeats across the three sets; only Mirage's basics repeat within one.
        per_set = [set(catalog['sets'][code]['names']) for code in pack.SETS]
        self.assertEqual(sum(len(s) for s in per_set), len(names))
        multiple = {row['name'] for row in cards if sum(1 for r in cards if r['name'] == row['name']) > 1}
        self.assertEqual(multiple, {'Plains', 'Island', 'Swamp', 'Mountain', 'Forest'})
        self.assertEqual([row['collector_number'] for row in cards if row['name'] == 'Forest'], ['347', '348', '349', '350'])
        self.assertTrue(all(row.get('lang', 'en') == 'en' and row['collector_number'].isdigit() for row in cards))
        # Reprints: exactly the names the core or an earlier pack already has.
        core = {name for _, name in first.assigned_pairs()}
        expansions = {}
        for path in sorted((pack.ROOT / 'packaging/card_packs').glob('*/cards*.json')):
            if path.parent == pack.SOURCE or path.parent.name == 'pack_1_dotp_complete':
                continue
            for row in pack.read_json(path):
                expansions.setdefault(row['name'], set()).add(row['set'])
        known = core | set(expansions)
        reprints = set(pack.read_json(pack.SOURCE / 'reprint_names.json'))
        self.assertEqual(names & known, reprints)
        self.assertEqual(len(reprints), 48)
        self.assertEqual(len(reprints - {'Plains', 'Island', 'Swamp', 'Mountain', 'Forest'}), 43)
        self.assertEqual(len(manifest['new_rules_identities']), 621)
        self.assertEqual(sorted(names - reprints), manifest['new_rules_identities'])
        self.assertEqual(manifest['counts'], {'published_printings': 684, 'named_set_entries': 669,
            'distinct_cards': 669, 'pack_card_entries': 684, 'reprint_entries': 48, 'new_rules_identities': 621})
        self.assertEqual(manifest['id'], 'pack-8')
        self.assertEqual(manifest['file_name'], pack.FILE_NAME)
        self.assertEqual(manifest['badge'], '8-MIR')
        self.assertEqual(manifest['minimum_game_version'], '0.50.11')
        # The shared names are exactly the reprints that live only in an
        # optional pack, keyed to the set whose script they reuse.
        shared = pack.shared_names()
        self.assertEqual(set(shared), reprints - core)
        self.assertEqual(len(shared), 31)
        order = ['fem', 'ice', 'hml', 'all', 'por', 'p02']
        for name, code in shared.items():
            self.assertIn(code, order)
            self.assertEqual(code, [c for c in order if c in expansions[name]][0], name)
            self.assertTrue((pack.ROOT / 'cards/sets' / code / (fetch_card_art.snake(name) + '.gd')).is_file(), name)
        self.assertEqual(shared['Archangel'], 'por')
        self.assertEqual(shared['Memory Lapse'], 'hml')
        self.assertEqual(shared['Undo'], 'p02')
        self.assertEqual(sorted(shared.values()).count('ice'), 4)
        # Every new identity has its trusted, script-only-in-the-game scaffold.
        for row in cards:
            if row['name'] in manifest['new_rules_identities']:
                script = pack.ROOT / 'cards/sets' / row['set'] / (fetch_card_art.snake(row['name']) + '.gd')
                self.assertTrue(script.is_file(), row['name'])
        self.assertEqual(len(pack.art_targets(Path('unused'))), 1368)
        self.assertEqual(len({str(path) for path, _, _ in pack.art_targets(Path('unused'))}), 1368)

    def test_deterministic_art_archive_and_no_scripts(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            for path, _, _ in pack.art_targets(root / 'art'):
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(self.JPEG)
            out = root / pack.FILE_NAME
            again = root / 'again' / pack.FILE_NAME
            pack.build(out, root / 'art')
            pack.build(again, root / 'art')
            self.assertEqual(out.read_bytes(), again.read_bytes())
            self.assertEqual(pack.verify(out)['checksums']['artwork']['files'], 2672)
            with zipfile.ZipFile(out) as archive:
                listed = archive.namelist()
                self.assertEqual(len(listed), pack.MAX_ENTRIES)
                self.assertFalse(any(name.endswith('.gd') for name in listed))
                shared = pack.shared_names()
                for name in pack.read_json(pack.SOURCE / 'reprint_names.json'):
                    stem = 'skin/cardart/' + fetch_card_art.snake(name)
                    self.assertEqual(stem + '.jpg' in listed, name in shared, name)
                self.assertIn('skin/cardart/b_sium_strip.jpg', listed)
                self.assertIn(pack.PREFIX + 'art/mir/forest__348.jpg', listed)
                self.assertIn(pack.PREFIX + 'art/vis/archangel_card.jpg', listed)
                self.assertIn(pack.PREFIX + 'art/wth/b_sium_strip.jpg', listed)
                self.assertNotIn('skin/cardart/forest.jpg', listed)
                self.assertTrue(all(name.startswith((pack.PREFIX, 'skin/cardart/')) for name in listed))

    def test_metadata_only_is_not_a_player_pack(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / pack.FILE_NAME
            pack.build(out, include_art=False)
            pack.verify(out, require_art=False)
            with self.assertRaises(ValueError):
                pack.verify(out)

    def test_wrong_name_and_unsupported_version_are_refused(self):
        with tempfile.TemporaryDirectory() as tmp:
            with self.assertRaisesRegex(ValueError, 'named exactly'):
                pack.build(Path(tmp) / 'Pack-8-Mirage.zip', include_art=False)
            out = Path(tmp) / pack.FILE_NAME
            pack.build(out, include_art=False)
            with zipfile.ZipFile(out) as archive:
                files = {name: archive.read(name) for name in archive.namelist()}
            manifest = files[pack.PREFIX + 'manifest.json'].decode('utf-8')
            files[pack.PREFIX + 'manifest.json'] = manifest.replace('"pack_format": 1', '"pack_format": 2').encode('utf-8')
            with zipfile.ZipFile(out, 'w') as archive:
                for name, value in files.items(): archive.writestr(name, value)
            with self.assertRaisesRegex(ValueError, 'manifest contract mismatch'):
                pack.verify(out, require_art=False)

    def test_extra_injected_and_duplicate_entries_are_refused(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / pack.FILE_NAME
            pack.build(out, include_art=False)
            with zipfile.ZipFile(out, 'a') as archive:
                archive.writestr('injected.gd', 'extends Node')
            with self.assertRaisesRegex(ValueError, 'unexpected'):
                pack.verify(out, require_art=False)
            pack.build(out, include_art=False)
            with zipfile.ZipFile(out, 'a') as archive:
                archive.writestr('../' + pack.PREFIX + 'art/mir/escape.jpg', self.JPEG)
            with self.assertRaisesRegex(ValueError, 'unexpected'):
                pack.verify(out, require_art=False)
            pack.build(out, include_art=False)
            with warnings.catch_warnings():
                warnings.simplefilter('ignore', UserWarning)
                with zipfile.ZipFile(out, 'a') as archive:
                    archive.writestr(pack.PREFIX + 'README.txt', 'duplicate')
            with self.assertRaisesRegex(ValueError, 'duplicate'):
                pack.verify(out, require_art=False)

    def test_failed_verification_does_not_replace_previous_pack(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / pack.FILE_NAME
            pack.build(out, include_art=False)
            before = out.read_bytes()
            with patch.object(pack, 'verify', side_effect=ValueError('test failure')):
                with self.assertRaises(ValueError):
                    pack.build(out, include_art=False)
            self.assertEqual(out.read_bytes(), before)
            self.assertEqual(list(out.parent.iterdir()), [out])

    def test_missing_artwork_refuses_before_output(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / pack.FILE_NAME
            with self.assertRaisesRegex(ValueError, 'fetch-art'):
                pack.build(out, Path(tmp) / 'empty-cache')
            self.assertFalse(out.exists())

    def test_uncompressed_size_is_bounded_before_reading_members(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / pack.FILE_NAME
            with zipfile.ZipFile(out, 'w', compression=zipfile.ZIP_DEFLATED) as archive:
                archive.writestr(pack.PREFIX + 'README.txt', b'x' * (8 * 1024 * 1024 + 1))
            with self.assertRaisesRegex(ValueError, 'size limits'):
                pack.verify(out)

    def test_metadata_tampering_is_rejected(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / pack.FILE_NAME
            pack.build(out, include_art=False)
            with zipfile.ZipFile(out) as archive:
                files = {name: archive.read(name) for name in archive.namelist()}
            files[pack.PREFIX + 'README.txt'] = b'changed'
            with zipfile.ZipFile(out, 'w') as archive:
                for name, value in files.items(): archive.writestr(name, value)
            with self.assertRaisesRegex(ValueError, 'trusted source'):
                pack.verify(out, require_art=False)

if __name__ == '__main__':
    unittest.main()
