"""Offline checks for the dedicated Portal construction tool."""
import base64
import tempfile
import subprocess
import unittest
import warnings
from unittest.mock import patch
import zipfile
from pathlib import Path

import pack_6_portal as pack
import pack_1_dotp_complete as first

class PackSixTests(unittest.TestCase):
    # A real one-pixel JPEG, generated by Godot; no downloaded card art.
    JPEG = base64.b64decode('/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAABAAEDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDmqKKK5zlP/9k=')
    def test_release_guard_refuses_each_numbered_pack_but_allows_source(self):
        source = (pack.ROOT / 'build_release.sh').read_text(encoding='utf-8')
        guard = 'guard_stage() {' + source.split('guard_stage() {', 1)[1].split('\n}\n', 1)[0] + '\n}\n'
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            (root / 'pack_6_portal.py').write_text('# construction source\n')
            def check():
                return subprocess.run(['bash', '-c', guard + 'guard_stage "$1"', 'guard-test', str(root)],
                                      capture_output=True, text=True)
            self.assertEqual(check().returncode, 0)
            for filename in ['Pack-1-DotP-complete.zip', 'Pack-2-Fallen-Empires.zip', 'Pack-3-Ice_Age.zip', 'Pack-4-Homelands.zip', pack.FILE_NAME]:
                archive = root / filename
                archive.write_bytes(b'local only')
                result = check()
                self.assertNotEqual(result.returncode, 0)
                self.assertIn('local artifacts', result.stderr)
                archive.unlink()

    def test_full_checklist_and_independent_names(self):
        manifest, catalog, cards, _ = pack.assembled()
        names = {row['name'] for row in cards}
        self.assertEqual(len(names), 200)
        self.assertEqual(len(pack.read_json(pack.SOURCE / 'cards.json')), 215)
        self.assertEqual(set(catalog['sets']), {'por'})
        self.assertEqual(set(catalog['sets']['por']['names']), names)
        previous = {name for _, name in first.assigned_pairs()}
        for path in (pack.ROOT / 'packaging/card_packs').glob('*/cards.json'):
            if path.parent == pack.SOURCE:
                continue
            previous.update(row['name'] for row in pack.read_json(path))
        self.assertEqual(names & previous, set(pack.read_json(pack.SOURCE / 'reprint_names.json')))
        self.assertEqual(len(manifest['new_rules_identities']), 173)
        self.assertEqual(len(set(manifest['new_rules_identities'])), 173)
        self.assertEqual(manifest['id'], 'pack-6')
        self.assertEqual(len(cards), 215)
        self.assertEqual(len(pack.art_targets(Path('unused'))), 430)
        self.assertEqual(len({str(path) for path, _, _ in pack.art_targets(Path('unused'))}), 430)
        self.assertEqual([row['collector_number'] for row in cards if row['name'] == 'Forest'], ['212', '213', '214', '215'])

    def test_deterministic_art_archive_and_no_scripts(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            for path, _, _ in pack.art_targets(root / 'art'):
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(self.JPEG)
            out = root / pack.FILE_NAME
            again = root / 'again' / pack.FILE_NAME
            pack.build(out, root / 'art')
            pack.build(again, root / 'art')
            self.assertEqual(out.read_bytes(), again.read_bytes())
            self.assertEqual(pack.verify(out)['checksums']['artwork']['files'], 788)
            with zipfile.ZipFile(out) as archive:
                self.assertEqual(len(archive.namelist()), 792)
                self.assertFalse(any(name.endswith('.gd') for name in archive.namelist()))
                for name in pack.read_json(pack.SOURCE / 'reprint_names.json'):
                    if name in pack.SHARED_NAMES:
                        continue
                    self.assertNotIn('skin/cardart/' + pack.fetch_card_art.snake(name) + '.jpg', archive.namelist())

    def test_metadata_only_is_not_a_player_pack(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / pack.FILE_NAME
            pack.build(out, include_art=False)
            pack.verify(out, require_art=False)
            with self.assertRaises(ValueError):
                pack.verify(out)

    def test_extra_and_duplicate_entries_are_refused(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / pack.FILE_NAME
            pack.build(out, include_art=False)
            with zipfile.ZipFile(out, 'a') as archive:
                archive.writestr('injected.gd', 'extends Node')
            with self.assertRaisesRegex(ValueError, 'unexpected'):
                pack.verify(out, require_art=False)
            pack.build(out, include_art=False)
            with warnings.catch_warnings():
                warnings.simplefilter('ignore', UserWarning)
                with zipfile.ZipFile(out, 'a') as archive:
                    archive.writestr(pack.PREFIX + 'README.txt', 'duplicate')
            with self.assertRaisesRegex(ValueError, 'duplicate'):
                pack.verify(out, require_art=False)

    def test_failed_verification_does_not_replace_previous_pack(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / pack.FILE_NAME
            pack.build(out, include_art=False)
            before = out.read_bytes()
            with patch.object(pack, 'verify', side_effect=ValueError('test failure')):
                with self.assertRaises(ValueError):
                    pack.build(out, include_art=False)
            self.assertEqual(out.read_bytes(), before)
            self.assertEqual(list(out.parent.iterdir()), [out])

    def test_uncompressed_size_is_bounded_before_reading_members(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / pack.FILE_NAME
            with zipfile.ZipFile(out, 'w', compression=zipfile.ZIP_DEFLATED) as archive:
                archive.writestr(pack.PREFIX + 'README.txt', b'x' * (8 * 1024 * 1024 + 1))
            with self.assertRaisesRegex(ValueError, 'size limits'):
                pack.verify(out)

    def test_metadata_tampering_is_rejected(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / pack.FILE_NAME
            pack.build(out, include_art=False)
            with zipfile.ZipFile(out) as archive:
                files = {name: archive.read(name) for name in archive.namelist()}
            files[pack.PREFIX + 'README.txt'] = b'changed'
            with zipfile.ZipFile(out, 'w') as archive:
                for name, value in files.items(): archive.writestr(name, value)
            with self.assertRaisesRegex(ValueError, 'trusted source'):
                pack.verify(out, require_art=False)

if __name__ == '__main__':
    unittest.main()
