extends CardScript
## Bird Maiden — {2}{R} — Creature — Human Bird — 1/2 — (4ed, common)
## Oracle: Flying
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Bird Maiden", "{2}{R}", Mtg.CardType.CREATURE) \
		.pt(1, 2) \
		.with_subtypes(["human", "bird"]) \
		.with_keywords([Mtg.Keyword.FLYING]) \
		.oracle("Flying")
