extends CardScript
## Bog Imp — {1}{B} — Creature — Imp — 1/1 — (4ed, common)
## Oracle: Flying (This creature can't be blocked except by creatures with flying or reach.)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Bog Imp", "{1}{B}", Mtg.CardType.CREATURE) \
		.pt(1, 1) \
		.with_subtypes(["imp"]) \
		.with_keywords([Mtg.Keyword.FLYING]) \
		.oracle("Flying (This creature can't be blocked except by creatures with flying or reach.)")
