extends CardScript
## Carnivorous Plant — {3}{G} — Creature — Plant Wall — 4/5 — (4ed, common)
## Oracle: Defender
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Carnivorous Plant", "{3}{G}", Mtg.CardType.CREATURE) \
		.pt(4, 5) \
		.with_subtypes(["plant", "wall"]) \
		.with_keywords([Mtg.Keyword.DEFENDER]) \
		.oracle("Defender")
