extends CardScript
## Dancing Scimitar — {4} — Artifact Creature — Spirit — 1/5 — (4ed, rare)
## Oracle: Flying (This creature can't be blocked except by creatures with flying or reach.)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Dancing Scimitar", "{4}", Mtg.CardType.ARTIFACT | Mtg.CardType.CREATURE) \
		.pt(1, 5) \
		.with_subtypes(["spirit"]) \
		.with_keywords([Mtg.Keyword.FLYING]) \
		.oracle("Flying (This creature can't be blocked except by creatures with flying or reach.)")
