extends CardScript
## Durkwood Boars — {4}{G} — Creature — Boar — 4/4 — (4ed, common)
## Oracle: (no rules text — vanilla creature)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Durkwood Boars", "{4}{G}", Mtg.CardType.CREATURE) \
		.pt(4, 4) \
		.with_subtypes(["boar"]) \
		.oracle("")
