extends CardScript
## Land Leeches — {1}{G}{G} — Creature — Leech — 2/2 — (4ed, common)
## Oracle: First strike
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Land Leeches", "{1}{G}{G}", Mtg.CardType.CREATURE) \
		.pt(2, 2) \
		.with_subtypes(["leech"]) \
		.with_keywords([Mtg.Keyword.FIRST_STRIKE]) \
		.oracle("First strike")
