extends CardScript
## Lost Soul — {1}{B}{B} — Creature — Spirit Minion — 2/1 — (4ed, common)
## Oracle: Swampwalk (This creature can't be blocked as long as defending player controls a Swamp.)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Lost Soul", "{1}{B}{B}", Mtg.CardType.CREATURE) \
		.pt(2, 1) \
		.with_subtypes(["spirit", "minion"]) \
		.with_landwalk(["swamp"]) \
		.oracle("Swampwalk (This creature can't be blocked as long as defending player controls a Swamp.)")
