extends CardScript
## Ornithopter — {0} — Artifact Creature — Thopter — 0/2 — (4ed, uncommon)
## Oracle: Flying
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Ornithopter", "{0}", Mtg.CardType.ARTIFACT | Mtg.CardType.CREATURE) \
		.pt(0, 2) \
		.with_subtypes(["thopter"]) \
		.with_keywords([Mtg.Keyword.FLYING]) \
		.oracle("Flying")
