extends CardScript
## Tundra Wolves — {W} — Creature — Wolf — 1/1 — (4ed, common)
## Oracle: First strike (This creature deals combat damage before creatures without first strike.)
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Tundra Wolves", "{W}", Mtg.CardType.CREATURE) \
		.pt(1, 1) \
		.with_subtypes(["wolf"]) \
		.with_keywords([Mtg.Keyword.FIRST_STRIKE]) \
		.oracle("First strike (This creature deals combat damage before creatures without first strike.)")
