extends CardScript
## Wall of Spears — {3} — Artifact Creature — Wall — 2/3 — (4ed, common)
## Oracle: Defender (This creature can't attack.)
##         First strike
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Wall of Spears", "{3}", Mtg.CardType.ARTIFACT | Mtg.CardType.CREATURE) \
		.pt(2, 3) \
		.with_subtypes(["wall"]) \
		.with_keywords([Mtg.Keyword.DEFENDER, Mtg.Keyword.FIRST_STRIKE]) \
		.oracle("Defender (This creature can't attack.)\nFirst strike")
