extends CardScript
## Yotian Soldier — {3} — Artifact Creature — Soldier — 1/4 — (4ed, common)
## Oracle: Vigilance
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Yotian Soldier", "{3}", Mtg.CardType.ARTIFACT | Mtg.CardType.CREATURE) \
		.pt(1, 4) \
		.with_subtypes(["soldier"]) \
		.with_keywords([Mtg.Keyword.VIGILANCE]) \
		.oracle("Vigilance")
