extends CardScript
## Zephyr Falcon — {1}{U} — Creature — Bird — 1/1 — (4ed, common)
## Oracle: Flying, vigilance
##
## Stats-and-keywords card generated from Scryfall data.
## AUTOGENERATED — regenerated by tools/gen_cards.py; hand-edit only after removing this marker line.


func build() -> CardData:
	return CardData.new("Zephyr Falcon", "{1}{U}", Mtg.CardType.CREATURE) \
		.pt(1, 1) \
		.with_subtypes(["bird"]) \
		.with_keywords([Mtg.Keyword.FLYING, Mtg.Keyword.VIGILANCE]) \
		.oracle("Flying, vigilance")
